-- Revert: schemas/myapp_auth_public/tables/principal_scope_overrides/triggers/principal_scope_overrides_guard_step_up_upd_tg


DROP TRIGGER principal_scope_overrides_guard_step_up_upd_tg ON myapp_auth_public.principal_scope_overrides;


