/**
 * PrincipalScopeOverride model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PrincipalScopeOverride,
  PrincipalScopeOverrideWithRelations,
  PrincipalScopeOverrideSelect,
  PrincipalScopeOverrideFilter,
  PrincipalScopeOverrideOrderBy,
  CreatePrincipalScopeOverrideInput,
  UpdatePrincipalScopeOverrideInput,
  PrincipalScopeOverridePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PrincipalScopeOverrideModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PrincipalScopeOverrideSelect>(
    args: FindManyArgs<S, PrincipalScopeOverrideFilter, PrincipalScopeOverrideOrderBy> & {
      select: S;
    } & StrictSelect<S, PrincipalScopeOverrideSelect>
  ): QueryBuilder<{
    principalScopeOverrides: ConnectionResult<
      InferSelectResult<PrincipalScopeOverrideWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PrincipalScopeOverride',
      'principalScopeOverrides',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PrincipalScopeOverrideFilter',
      'PrincipalScopeOverrideOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PrincipalScopeOverride',
      fieldName: 'principalScopeOverrides',
      document,
      variables,
    });
  }
  findFirst<S extends PrincipalScopeOverrideSelect>(
    args: FindFirstArgs<S, PrincipalScopeOverrideFilter, PrincipalScopeOverrideOrderBy> & {
      select: S;
    } & StrictSelect<S, PrincipalScopeOverrideSelect>
  ): QueryBuilder<{
    principalScopeOverride: InferSelectResult<PrincipalScopeOverrideWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PrincipalScopeOverride',
      'principalScopeOverrides',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PrincipalScopeOverrideFilter',
      'PrincipalScopeOverrideOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PrincipalScopeOverride',
      fieldName: 'principalScopeOverride',
      document,
      variables,
      transform: (data: {
        principalScopeOverrides?: {
          nodes?: InferSelectResult<PrincipalScopeOverrideWithRelations, S>[];
        };
      }) => ({
        principalScopeOverride: data.principalScopeOverrides?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PrincipalScopeOverrideSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PrincipalScopeOverrideSelect>
  ): QueryBuilder<{
    principalScopeOverride: InferSelectResult<PrincipalScopeOverrideWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PrincipalScopeOverride',
      'principalScopeOverrides',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PrincipalScopeOverrideFilter',
      'PrincipalScopeOverrideOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PrincipalScopeOverride',
      fieldName: 'principalScopeOverride',
      document,
      variables,
      transform: (data: {
        principalScopeOverrides?: {
          nodes?: InferSelectResult<PrincipalScopeOverrideWithRelations, S>[];
        };
      }) => ({
        principalScopeOverride: data.principalScopeOverrides?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PrincipalScopeOverrideSelect>(
    args: CreateArgs<S, CreatePrincipalScopeOverrideInput['principalScopeOverride']> & {
      select: S;
    } & StrictSelect<S, PrincipalScopeOverrideSelect>
  ): QueryBuilder<{
    createPrincipalScopeOverride: {
      principalScopeOverride: InferSelectResult<PrincipalScopeOverrideWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PrincipalScopeOverride',
      'createPrincipalScopeOverride',
      'principalScopeOverride',
      args.select,
      args.data,
      'CreatePrincipalScopeOverrideInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PrincipalScopeOverride',
      fieldName: 'createPrincipalScopeOverride',
      document,
      variables,
    });
  }
}
