/**
 * UserConnectedAccount model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  UserConnectedAccount,
  UserConnectedAccountWithRelations,
  UserConnectedAccountSelect,
  UserConnectedAccountFilter,
  UserConnectedAccountOrderBy,
  CreateUserConnectedAccountInput,
  UpdateUserConnectedAccountInput,
  UserConnectedAccountPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class UserConnectedAccountModel {
  constructor(private client: OrmClient) {}
  findMany<S extends UserConnectedAccountSelect>(
    args: FindManyArgs<S, UserConnectedAccountFilter, UserConnectedAccountOrderBy> & {
      select: S;
    } & StrictSelect<S, UserConnectedAccountSelect>
  ): QueryBuilder<{
    userConnectedAccounts: ConnectionResult<
      InferSelectResult<UserConnectedAccountWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'UserConnectedAccount',
      'userConnectedAccounts',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'UserConnectedAccountFilter',
      'UserConnectedAccountOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'UserConnectedAccount',
      fieldName: 'userConnectedAccounts',
      document,
      variables,
    });
  }
  findFirst<S extends UserConnectedAccountSelect>(
    args: FindFirstArgs<S, UserConnectedAccountFilter, UserConnectedAccountOrderBy> & {
      select: S;
    } & StrictSelect<S, UserConnectedAccountSelect>
  ): QueryBuilder<{
    userConnectedAccount: InferSelectResult<UserConnectedAccountWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'UserConnectedAccount',
      'userConnectedAccounts',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'UserConnectedAccountFilter',
      'UserConnectedAccountOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'UserConnectedAccount',
      fieldName: 'userConnectedAccount',
      document,
      variables,
      transform: (data: {
        userConnectedAccounts?: {
          nodes?: InferSelectResult<UserConnectedAccountWithRelations, S>[];
        };
      }) => ({
        userConnectedAccount: data.userConnectedAccounts?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends UserConnectedAccountSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, UserConnectedAccountSelect>
  ): QueryBuilder<{
    userConnectedAccount: InferSelectResult<UserConnectedAccountWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'UserConnectedAccount',
      'userConnectedAccounts',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'UserConnectedAccountFilter',
      'UserConnectedAccountOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'UserConnectedAccount',
      fieldName: 'userConnectedAccount',
      document,
      variables,
      transform: (data: {
        userConnectedAccounts?: {
          nodes?: InferSelectResult<UserConnectedAccountWithRelations, S>[];
        };
      }) => ({
        userConnectedAccount: data.userConnectedAccounts?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends UserConnectedAccountSelect>(
    args: CreateArgs<S, CreateUserConnectedAccountInput['userConnectedAccount']> & {
      select: S;
    } & StrictSelect<S, UserConnectedAccountSelect>
  ): QueryBuilder<{
    createUserConnectedAccount: {
      userConnectedAccount: InferSelectResult<UserConnectedAccountWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'UserConnectedAccount',
      'createUserConnectedAccount',
      'userConnectedAccount',
      args.select,
      args.data,
      'CreateUserConnectedAccountInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'UserConnectedAccount',
      fieldName: 'createUserConnectedAccount',
      document,
      variables,
    });
  }
}
