-- Verify: schemas/platform_routing_public/tables/platform_route_bindings/indexes/platform_route_bindings_domain_id_is_active_idx


SELECT verify_index('platform_routing_public.platform_route_bindings', 'platform_route_bindings_domain_id_is_active_idx');