-- Revert: schemas/routing_public/tables/platform_email_provider_accounts/columns/credentials_secret_name/alterations/alt0000000002


COMMENT ON COLUMN routing_public.platform_email_provider_accounts.credentials_secret_name IS NULL;