-- Revert: schemas/myapp_memberships_public/tables/app_capability_default_capabilities/constraints/app_capability_default_capabilities_pkey/constraint


ALTER TABLE myapp_memberships_public.app_capability_default_capabilities 
  DROP CONSTRAINT app_capability_default_capabilities_pkey;


