-- Revert: schemas/catalog_private/tables/resource_installations/indexes/resource_installations_owner_scope_owner_key_idx


DROP INDEX catalog_private.resource_installations_owner_scope_owner_key_idx;