-- Revert: schemas/platform_routing_public/tables/platform_hostname_bindings/columns/verification_status/alterations/alt0000000001


COMMENT ON COLUMN platform_routing_public.platform_hostname_bindings.verification_status IS NULL;