-- Revert: schemas/catalog_private/tables/functions/indexes/functions_database_id_owner_scope_owner_key_task_identifier_idx


DROP INDEX catalog_private.functions_database_id_owner_scope_owner_key_task_identifier_idx;