-- Revert: schemas/myapp_memberships_public/tables/app_memberships/triggers/_00020_app_memberships_profiles_seed_utrg


DROP TRIGGER _00020_app_memberships_profiles_seed_utrg ON myapp_memberships_public.app_memberships;


