-- Revert: schemas/myapp_memberships_public/tables/org_capability_default_grants/constraints/org_capability_default_grants_grantor_id_fkey/constraint


ALTER TABLE myapp_memberships_public.org_capability_default_grants 
  DROP CONSTRAINT org_capability_default_grants_grantor_id_fkey;


