-- Revert: schemas/myapp_memberships_public/tables/org_memberships/triggers/_00020_org_memberships_profiles_seed_utrg


DROP TRIGGER _00020_org_memberships_profiles_seed_utrg ON myapp_memberships_public.org_memberships;


