-- Revert: schemas/routing_public/tables/platform_email_provider_accounts/columns/webhook_signing_secret_name/alterations/alt0000000001


COMMENT ON COLUMN routing_public.platform_email_provider_accounts.webhook_signing_secret_name IS NULL;