-- Revert: schemas/routing_public/tables/platform_email_site_identities/constraints/platform_email_site_identities_email_identity_id_fkey/constraint


ALTER TABLE routing_public.platform_email_site_identities 
  DROP CONSTRAINT platform_email_site_identities_email_identity_id_fkey RESTRICT;