-- Verify: schemas/platform_routing_public/tables/platform_routes/indexes/platform_routes_domain_id_path_method_is_active_idx


SELECT verify_index('platform_routing_public.platform_routes', 'platform_routes_domain_id_path_method_is_active_idx');