/**
 * User email addresses with verification and primary-email management
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { emailKeys } from '../query-keys';
import type { EmailSelect, EmailWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { EmailSelect, EmailWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const emailQueryKey = emailKeys.detail;
/**
 * User email addresses with verification and primary-email management
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useEmailQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useEmailQuery<
  S extends EmailSelect,
  TData = {
    email: InferSelectResult<EmailWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, EmailSelect>;
  } & Omit<
    UseQueryOptions<
      {
        email: InferSelectResult<EmailWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useEmailQuery(
  params: {
    id: string;
    selection: SelectionConfig<EmailSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<EmailSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: emailKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .email.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * User email addresses with verification and primary-email management
 *
 * @example
 * ```ts
 * const data = await fetchEmailQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchEmailQuery<S extends EmailSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, EmailSelect>;
}): Promise<{
  email: InferSelectResult<EmailWithRelations, S> | null;
}>;
export async function fetchEmailQuery(params: {
  id: string;
  selection: SelectionConfig<EmailSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<EmailSelect>(params.selection);
  return getClient()
    .email.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * User email addresses with verification and primary-email management
 *
 * @example
 * ```ts
 * await prefetchEmailQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchEmailQuery<S extends EmailSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, EmailSelect>;
  }
): Promise<void>;
export async function prefetchEmailQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<EmailSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<EmailSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: emailKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .email.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
