/**
 * Scoped sub-identities (API keys and agents) with precomputed SPRT
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { principalKeys } from '../query-keys';
import type { PrincipalSelect, PrincipalWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { PrincipalSelect, PrincipalWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const principalQueryKey = principalKeys.detail;
/**
 * Scoped sub-identities (API keys and agents) with precomputed SPRT
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePrincipalQuery({
 *   principalId: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePrincipalQuery<
  S extends PrincipalSelect,
  TData = {
    principal: InferSelectResult<PrincipalWithRelations, S> | null;
  },
>(
  params: {
    principalId: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PrincipalSelect>;
  } & Omit<
    UseQueryOptions<
      {
        principal: InferSelectResult<PrincipalWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePrincipalQuery(
  params: {
    principalId: string;
    selection: SelectionConfig<PrincipalSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PrincipalSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: principalKeys.detail(params.principalId),
    queryFn: () =>
      getClient()
        .principal.findOne({
          principalId: params.principalId,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Scoped sub-identities (API keys and agents) with precomputed SPRT
 *
 * @example
 * ```ts
 * const data = await fetchPrincipalQuery({
 *   principalId: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPrincipalQuery<S extends PrincipalSelect>(params: {
  principalId: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PrincipalSelect>;
}): Promise<{
  principal: InferSelectResult<PrincipalWithRelations, S> | null;
}>;
export async function fetchPrincipalQuery(params: {
  principalId: string;
  selection: SelectionConfig<PrincipalSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PrincipalSelect>(params.selection);
  return getClient()
    .principal.findOne({
      principalId: params.principalId,
      select: args.select,
    })
    .unwrap();
}
/**
 * Scoped sub-identities (API keys and agents) with precomputed SPRT
 *
 * @example
 * ```ts
 * await prefetchPrincipalQuery(queryClient, { principalId: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPrincipalQuery<S extends PrincipalSelect>(
  queryClient: QueryClient,
  params: {
    principalId: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PrincipalSelect>;
  }
): Promise<void>;
export async function prefetchPrincipalQuery(
  queryClient: QueryClient,
  params: {
    principalId: string;
    selection: SelectionConfig<PrincipalSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PrincipalSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: principalKeys.detail(params.principalId),
    queryFn: () =>
      getClient()
        .principal.findOne({
          principalId: params.principalId,
          select: args.select,
        })
        .unwrap(),
  });
}
