/**
 * User phone numbers with country code, verification, and primary-number management
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { phoneNumberKeys } from '../query-keys';
import type {
  PhoneNumberSelect,
  PhoneNumberWithRelations,
  PhoneNumberFilter,
  PhoneNumberOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  PhoneNumberSelect,
  PhoneNumberWithRelations,
  PhoneNumberFilter,
  PhoneNumberOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const phoneNumbersQueryKey = phoneNumberKeys.list;
/**
 * User phone numbers with country code, verification, and primary-number management
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePhoneNumbersQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function usePhoneNumbersQuery<
  S extends PhoneNumberSelect,
  TData = {
    phoneNumbers: ConnectionResult<InferSelectResult<PhoneNumberWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, PhoneNumberFilter, PhoneNumberOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, PhoneNumberSelect>;
  } & Omit<
    UseQueryOptions<
      {
        phoneNumbers: ConnectionResult<InferSelectResult<PhoneNumberWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePhoneNumbersQuery(
  params: {
    selection: ListSelectionConfig<PhoneNumberSelect, PhoneNumberFilter, PhoneNumberOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<PhoneNumberSelect, PhoneNumberFilter, PhoneNumberOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: phoneNumberKeys.list(args),
    queryFn: () => getClient().phoneNumber.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * User phone numbers with country code, verification, and primary-number management
 *
 * @example
 * ```ts
 * const data = await fetchPhoneNumbersQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchPhoneNumbersQuery<S extends PhoneNumberSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, PhoneNumberFilter, PhoneNumberOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, PhoneNumberSelect>;
}): Promise<{
  phoneNumbers: ConnectionResult<InferSelectResult<PhoneNumberWithRelations, S>>;
}>;
export async function fetchPhoneNumbersQuery(params: {
  selection: ListSelectionConfig<PhoneNumberSelect, PhoneNumberFilter, PhoneNumberOrderBy>;
}) {
  const args = buildListSelectionArgs<PhoneNumberSelect, PhoneNumberFilter, PhoneNumberOrderBy>(
    params.selection
  );
  return getClient().phoneNumber.findMany(args).unwrap();
}
/**
 * User phone numbers with country code, verification, and primary-number management
 *
 * @example
 * ```ts
 * await prefetchPhoneNumbersQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchPhoneNumbersQuery<S extends PhoneNumberSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, PhoneNumberFilter, PhoneNumberOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, PhoneNumberSelect>;
  }
): Promise<void>;
export async function prefetchPhoneNumbersQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<PhoneNumberSelect, PhoneNumberFilter, PhoneNumberOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<PhoneNumberSelect, PhoneNumberFilter, PhoneNumberOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: phoneNumberKeys.list(args),
    queryFn: () => getClient().phoneNumber.findMany(args).unwrap(),
  });
}
