/**
 * Single item query hook for RoleType
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { roleTypeKeys } from '../query-keys';
import type { RoleTypeSelect, RoleTypeWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { RoleTypeSelect, RoleTypeWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const roleTypeQueryKey = roleTypeKeys.detail;
/**
 * Query hook for fetching a single RoleType
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useRoleTypeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useRoleTypeQuery<
  S extends RoleTypeSelect,
  TData = {
    roleType: InferSelectResult<RoleTypeWithRelations, S> | null;
  },
>(
  params: {
    id: number;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, RoleTypeSelect>;
  } & Omit<
    UseQueryOptions<
      {
        roleType: InferSelectResult<RoleTypeWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useRoleTypeQuery(
  params: {
    id: number;
    selection: SelectionConfig<RoleTypeSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<RoleTypeSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: roleTypeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .roleType.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single RoleType without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchRoleTypeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchRoleTypeQuery<S extends RoleTypeSelect>(params: {
  id: number;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, RoleTypeSelect>;
}): Promise<{
  roleType: InferSelectResult<RoleTypeWithRelations, S> | null;
}>;
export async function fetchRoleTypeQuery(params: {
  id: number;
  selection: SelectionConfig<RoleTypeSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<RoleTypeSelect>(params.selection);
  return getClient()
    .roleType.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single RoleType for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchRoleTypeQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchRoleTypeQuery<S extends RoleTypeSelect>(
  queryClient: QueryClient,
  params: {
    id: number;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, RoleTypeSelect>;
  }
): Promise<void>;
export async function prefetchRoleTypeQuery(
  queryClient: QueryClient,
  params: {
    id: number;
    selection: SelectionConfig<RoleTypeSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<RoleTypeSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: roleTypeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .roleType.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
