-- Revert: schemas/routing_public/tables/site_app_links/constraints/site_app_links_site_id_platform_app_identifier_key/constraint


ALTER TABLE routing_public.site_app_links 
  DROP CONSTRAINT site_app_links_site_id_platform_app_identifier_key RESTRICT;