/**
 * Custom query operations
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import { QueryBuilder, buildCustomDocument } from '../query-builder';
import type { InferSelectResult, StrictSelect } from '../select-types';
import type {
  User,
  UserSelect,
  AppPermissionConnection,
  OrgPermissionConnection,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export interface RequireStepUpVariables {
  stepUpType?: string;
}
export interface AppPermissionsGetPaddedMaskVariables {
  mask?: string;
}
export interface OrgPermissionsGetPaddedMaskVariables {
  mask?: string;
}
export interface OrgIsManagerOfVariables {
  targetEntityId?: string;
  managerId?: string;
  userId?: string;
  maxDepth?: number;
}
export interface AppPermissionsGetMaskVariables {
  ids?: string[];
}
export interface OrgPermissionsGetMaskVariables {
  ids?: string[];
}
export interface AppPermissionsGetMaskByNamesVariables {
  names?: string[];
}
export interface OrgPermissionsGetMaskByNamesVariables {
  names?: string[];
}
export interface AppPermissionsGetByMaskVariables {
  mask?: string;
  /** Only read the first `n` values of the set. */
  first?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
}
export interface OrgPermissionsGetByMaskVariables {
  mask?: string;
  /** Only read the first `n` values of the set. */
  first?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
}
export function createQueryOperations(client: OrmClient) {
  return {
    currentUserId: (options?: { select?: Record<string, unknown> }) =>
      new QueryBuilder<{
        currentUserId: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentUserId',
        fieldName: 'currentUserId',
        ...buildCustomDocument(
          'query',
          'CurrentUserId',
          'currentUserId',
          options?.select,
          undefined,
          [],
          connectionFieldsMap,
          undefined
        ),
      }),
    currentUserAgent: (options?: { select?: Record<string, unknown> }) =>
      new QueryBuilder<{
        currentUserAgent: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentUserAgent',
        fieldName: 'currentUserAgent',
        ...buildCustomDocument(
          'query',
          'CurrentUserAgent',
          'currentUserAgent',
          options?.select,
          undefined,
          [],
          connectionFieldsMap,
          undefined
        ),
      }),
    currentIpAddress: (options?: { select?: Record<string, unknown> }) =>
      new QueryBuilder<{
        currentIpAddress: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentIpAddress',
        fieldName: 'currentIpAddress',
        ...buildCustomDocument(
          'query',
          'CurrentIpAddress',
          'currentIpAddress',
          options?.select,
          undefined,
          [],
          connectionFieldsMap,
          undefined
        ),
      }),
    requireStepUp: (
      args: RequireStepUpVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        requireStepUp: boolean | null;
      }>({
        client,
        operation: 'query',
        operationName: 'RequireStepUp',
        fieldName: 'requireStepUp',
        ...buildCustomDocument(
          'query',
          'RequireStepUp',
          'requireStepUp',
          options?.select,
          args,
          [
            {
              name: 'stepUpType',
              type: 'String',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appPermissionsGetPaddedMask: (
      args: AppPermissionsGetPaddedMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appPermissionsGetPaddedMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppPermissionsGetPaddedMask',
        fieldName: 'appPermissionsGetPaddedMask',
        ...buildCustomDocument(
          'query',
          'AppPermissionsGetPaddedMask',
          'appPermissionsGetPaddedMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgPermissionsGetPaddedMask: (
      args: OrgPermissionsGetPaddedMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgPermissionsGetPaddedMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgPermissionsGetPaddedMask',
        fieldName: 'orgPermissionsGetPaddedMask',
        ...buildCustomDocument(
          'query',
          'OrgPermissionsGetPaddedMask',
          'orgPermissionsGetPaddedMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgIsManagerOf: (
      args: OrgIsManagerOfVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgIsManagerOf: boolean | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgIsManagerOf',
        fieldName: 'orgIsManagerOf',
        ...buildCustomDocument(
          'query',
          'OrgIsManagerOf',
          'orgIsManagerOf',
          options?.select,
          args,
          [
            {
              name: 'targetEntityId',
              type: 'UUID',
            },
            {
              name: 'managerId',
              type: 'UUID',
            },
            {
              name: 'userId',
              type: 'UUID',
            },
            {
              name: 'maxDepth',
              type: 'Int',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appPermissionsGetMask: (
      args: AppPermissionsGetMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appPermissionsGetMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppPermissionsGetMask',
        fieldName: 'appPermissionsGetMask',
        ...buildCustomDocument(
          'query',
          'AppPermissionsGetMask',
          'appPermissionsGetMask',
          options?.select,
          args,
          [
            {
              name: 'ids',
              type: '[UUID]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgPermissionsGetMask: (
      args: OrgPermissionsGetMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgPermissionsGetMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgPermissionsGetMask',
        fieldName: 'orgPermissionsGetMask',
        ...buildCustomDocument(
          'query',
          'OrgPermissionsGetMask',
          'orgPermissionsGetMask',
          options?.select,
          args,
          [
            {
              name: 'ids',
              type: '[UUID]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appPermissionsGetMaskByNames: (
      args: AppPermissionsGetMaskByNamesVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appPermissionsGetMaskByNames: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppPermissionsGetMaskByNames',
        fieldName: 'appPermissionsGetMaskByNames',
        ...buildCustomDocument(
          'query',
          'AppPermissionsGetMaskByNames',
          'appPermissionsGetMaskByNames',
          options?.select,
          args,
          [
            {
              name: 'names',
              type: '[String]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgPermissionsGetMaskByNames: (
      args: OrgPermissionsGetMaskByNamesVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgPermissionsGetMaskByNames: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgPermissionsGetMaskByNames',
        fieldName: 'orgPermissionsGetMaskByNames',
        ...buildCustomDocument(
          'query',
          'OrgPermissionsGetMaskByNames',
          'orgPermissionsGetMaskByNames',
          options?.select,
          args,
          [
            {
              name: 'names',
              type: '[String]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appPermissionsGetByMask: (
      args: AppPermissionsGetByMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appPermissionsGetByMask: AppPermissionConnection | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppPermissionsGetByMask',
        fieldName: 'appPermissionsGetByMask',
        ...buildCustomDocument(
          'query',
          'AppPermissionsGetByMask',
          'appPermissionsGetByMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
            {
              name: 'first',
              type: 'Int',
            },
            {
              name: 'offset',
              type: 'Int',
            },
            {
              name: 'after',
              type: 'Cursor',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgPermissionsGetByMask: (
      args: OrgPermissionsGetByMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgPermissionsGetByMask: OrgPermissionConnection | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgPermissionsGetByMask',
        fieldName: 'orgPermissionsGetByMask',
        ...buildCustomDocument(
          'query',
          'OrgPermissionsGetByMask',
          'orgPermissionsGetByMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
            {
              name: 'first',
              type: 'Int',
            },
            {
              name: 'offset',
              type: 'Int',
            },
            {
              name: 'after',
              type: 'Cursor',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    currentUser: <S extends UserSelect>(
      options: {
        select: S;
      } & StrictSelect<S, UserSelect>
    ) =>
      new QueryBuilder<{
        currentUser: InferSelectResult<User, S> | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentUser',
        fieldName: 'currentUser',
        ...buildCustomDocument(
          'query',
          'CurrentUser',
          'currentUser',
          options.select,
          undefined,
          [],
          connectionFieldsMap,
          'User'
        ),
      }),
  };
}
