-- Revert: schemas/myapp_memberships_public/tables/org_capability_default_capabilities/indexes/org_capability_default_capabilities_capability_id_entity_id_idx


DROP INDEX myapp_memberships_public.org_capability_default_capabilities_capability_id_entity_id_idx;


