/**
 * AppProfilePermission model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppProfilePermission,
  AppProfilePermissionWithRelations,
  AppProfilePermissionSelect,
  AppProfilePermissionFilter,
  AppProfilePermissionOrderBy,
  CreateAppProfilePermissionInput,
  UpdateAppProfilePermissionInput,
  AppProfilePermissionPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppProfilePermissionModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppProfilePermissionSelect>(
    args: FindManyArgs<S, AppProfilePermissionFilter, AppProfilePermissionOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfilePermissionSelect>
  ): QueryBuilder<{
    appProfilePermissions: ConnectionResult<
      InferSelectResult<AppProfilePermissionWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfilePermission',
      'appProfilePermissions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppProfilePermissionFilter',
      'AppProfilePermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfilePermission',
      fieldName: 'appProfilePermissions',
      document,
      variables,
    });
  }
  findFirst<S extends AppProfilePermissionSelect>(
    args: FindFirstArgs<S, AppProfilePermissionFilter, AppProfilePermissionOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfilePermissionSelect>
  ): QueryBuilder<{
    appProfilePermission: InferSelectResult<AppProfilePermissionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppProfilePermission',
      'appProfilePermissions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppProfilePermissionFilter',
      'AppProfilePermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfilePermission',
      fieldName: 'appProfilePermission',
      document,
      variables,
      transform: (data: {
        appProfilePermissions?: {
          nodes?: InferSelectResult<AppProfilePermissionWithRelations, S>[];
        };
      }) => ({
        appProfilePermission: data.appProfilePermissions?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppProfilePermissionSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppProfilePermissionSelect>
  ): QueryBuilder<{
    appProfilePermission: InferSelectResult<AppProfilePermissionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfilePermission',
      'appProfilePermissions',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppProfilePermissionFilter',
      'AppProfilePermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfilePermission',
      fieldName: 'appProfilePermission',
      document,
      variables,
      transform: (data: {
        appProfilePermissions?: {
          nodes?: InferSelectResult<AppProfilePermissionWithRelations, S>[];
        };
      }) => ({
        appProfilePermission: data.appProfilePermissions?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppProfilePermissionSelect>(
    args: CreateArgs<S, CreateAppProfilePermissionInput['appProfilePermission']> & {
      select: S;
    } & StrictSelect<S, AppProfilePermissionSelect>
  ): QueryBuilder<{
    createAppProfilePermission: {
      appProfilePermission: InferSelectResult<AppProfilePermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppProfilePermission',
      'createAppProfilePermission',
      'appProfilePermission',
      args.select,
      args.data,
      'CreateAppProfilePermissionInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfilePermission',
      fieldName: 'createAppProfilePermission',
      document,
      variables,
    });
  }
  update<S extends AppProfilePermissionSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppProfilePermissionPatch
    > & {
      select: S;
    } & StrictSelect<S, AppProfilePermissionSelect>
  ): QueryBuilder<{
    updateAppProfilePermission: {
      appProfilePermission: InferSelectResult<AppProfilePermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppProfilePermission',
      'updateAppProfilePermission',
      'appProfilePermission',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppProfilePermissionInput',
      'id',
      'appProfilePermissionPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfilePermission',
      fieldName: 'updateAppProfilePermission',
      document,
      variables,
    });
  }
  delete<S extends AppProfilePermissionSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppProfilePermissionSelect>
  ): QueryBuilder<{
    deleteAppProfilePermission: {
      appProfilePermission: InferSelectResult<AppProfilePermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppProfilePermission',
      'deleteAppProfilePermission',
      'appProfilePermission',
      {
        id: args.where.id,
      },
      'DeleteAppProfilePermissionInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfilePermission',
      fieldName: 'deleteAppProfilePermission',
      document,
      variables,
    });
  }
}
