/**
 * AppPermissionDefaultGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppPermissionDefaultGrant,
  AppPermissionDefaultGrantWithRelations,
  AppPermissionDefaultGrantSelect,
  AppPermissionDefaultGrantFilter,
  AppPermissionDefaultGrantOrderBy,
  CreateAppPermissionDefaultGrantInput,
  UpdateAppPermissionDefaultGrantInput,
  AppPermissionDefaultGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppPermissionDefaultGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppPermissionDefaultGrantSelect>(
    args: FindManyArgs<S, AppPermissionDefaultGrantFilter, AppPermissionDefaultGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppPermissionDefaultGrantSelect>
  ): QueryBuilder<{
    appPermissionDefaultGrants: ConnectionResult<
      InferSelectResult<AppPermissionDefaultGrantWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppPermissionDefaultGrant',
      'appPermissionDefaultGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppPermissionDefaultGrantFilter',
      'AppPermissionDefaultGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppPermissionDefaultGrant',
      fieldName: 'appPermissionDefaultGrants',
      document,
      variables,
    });
  }
  findFirst<S extends AppPermissionDefaultGrantSelect>(
    args: FindFirstArgs<S, AppPermissionDefaultGrantFilter, AppPermissionDefaultGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppPermissionDefaultGrantSelect>
  ): QueryBuilder<{
    appPermissionDefaultGrant: InferSelectResult<AppPermissionDefaultGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppPermissionDefaultGrant',
      'appPermissionDefaultGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppPermissionDefaultGrantFilter',
      'AppPermissionDefaultGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppPermissionDefaultGrant',
      fieldName: 'appPermissionDefaultGrant',
      document,
      variables,
      transform: (data: {
        appPermissionDefaultGrants?: {
          nodes?: InferSelectResult<AppPermissionDefaultGrantWithRelations, S>[];
        };
      }) => ({
        appPermissionDefaultGrant: data.appPermissionDefaultGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppPermissionDefaultGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppPermissionDefaultGrantSelect>
  ): QueryBuilder<{
    appPermissionDefaultGrant: InferSelectResult<AppPermissionDefaultGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppPermissionDefaultGrant',
      'appPermissionDefaultGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppPermissionDefaultGrantFilter',
      'AppPermissionDefaultGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppPermissionDefaultGrant',
      fieldName: 'appPermissionDefaultGrant',
      document,
      variables,
      transform: (data: {
        appPermissionDefaultGrants?: {
          nodes?: InferSelectResult<AppPermissionDefaultGrantWithRelations, S>[];
        };
      }) => ({
        appPermissionDefaultGrant: data.appPermissionDefaultGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppPermissionDefaultGrantSelect>(
    args: CreateArgs<S, CreateAppPermissionDefaultGrantInput['appPermissionDefaultGrant']> & {
      select: S;
    } & StrictSelect<S, AppPermissionDefaultGrantSelect>
  ): QueryBuilder<{
    createAppPermissionDefaultGrant: {
      appPermissionDefaultGrant: InferSelectResult<AppPermissionDefaultGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppPermissionDefaultGrant',
      'createAppPermissionDefaultGrant',
      'appPermissionDefaultGrant',
      args.select,
      args.data,
      'CreateAppPermissionDefaultGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppPermissionDefaultGrant',
      fieldName: 'createAppPermissionDefaultGrant',
      document,
      variables,
    });
  }
  update<S extends AppPermissionDefaultGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppPermissionDefaultGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, AppPermissionDefaultGrantSelect>
  ): QueryBuilder<{
    updateAppPermissionDefaultGrant: {
      appPermissionDefaultGrant: InferSelectResult<AppPermissionDefaultGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppPermissionDefaultGrant',
      'updateAppPermissionDefaultGrant',
      'appPermissionDefaultGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppPermissionDefaultGrantInput',
      'id',
      'appPermissionDefaultGrantPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppPermissionDefaultGrant',
      fieldName: 'updateAppPermissionDefaultGrant',
      document,
      variables,
    });
  }
  delete<S extends AppPermissionDefaultGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppPermissionDefaultGrantSelect>
  ): QueryBuilder<{
    deleteAppPermissionDefaultGrant: {
      appPermissionDefaultGrant: InferSelectResult<AppPermissionDefaultGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppPermissionDefaultGrant',
      'deleteAppPermissionDefaultGrant',
      'appPermissionDefaultGrant',
      {
        id: args.where.id,
      },
      'DeleteAppPermissionDefaultGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppPermissionDefaultGrant',
      fieldName: 'deleteAppPermissionDefaultGrant',
      document,
      variables,
    });
  }
}
