/**
 * OrgPermission model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgPermission,
  OrgPermissionWithRelations,
  OrgPermissionSelect,
  OrgPermissionFilter,
  OrgPermissionOrderBy,
  CreateOrgPermissionInput,
  UpdateOrgPermissionInput,
  OrgPermissionPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgPermissionModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgPermissionSelect>(
    args: FindManyArgs<S, OrgPermissionFilter, OrgPermissionOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgPermissionSelect>
  ): QueryBuilder<{
    orgPermissions: ConnectionResult<InferSelectResult<OrgPermissionWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgPermission',
      'orgPermissions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgPermissionFilter',
      'OrgPermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgPermission',
      fieldName: 'orgPermissions',
      document,
      variables,
    });
  }
  findFirst<S extends OrgPermissionSelect>(
    args: FindFirstArgs<S, OrgPermissionFilter, OrgPermissionOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgPermissionSelect>
  ): QueryBuilder<{
    orgPermission: InferSelectResult<OrgPermissionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgPermission',
      'orgPermissions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgPermissionFilter',
      'OrgPermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgPermission',
      fieldName: 'orgPermission',
      document,
      variables,
      transform: (data: {
        orgPermissions?: {
          nodes?: InferSelectResult<OrgPermissionWithRelations, S>[];
        };
      }) => ({
        orgPermission: data.orgPermissions?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgPermissionSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgPermissionSelect>
  ): QueryBuilder<{
    orgPermission: InferSelectResult<OrgPermissionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgPermission',
      'orgPermissions',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgPermissionFilter',
      'OrgPermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgPermission',
      fieldName: 'orgPermission',
      document,
      variables,
      transform: (data: {
        orgPermissions?: {
          nodes?: InferSelectResult<OrgPermissionWithRelations, S>[];
        };
      }) => ({
        orgPermission: data.orgPermissions?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgPermissionSelect>(
    args: CreateArgs<S, CreateOrgPermissionInput['orgPermission']> & {
      select: S;
    } & StrictSelect<S, OrgPermissionSelect>
  ): QueryBuilder<{
    createOrgPermission: {
      orgPermission: InferSelectResult<OrgPermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgPermission',
      'createOrgPermission',
      'orgPermission',
      args.select,
      args.data,
      'CreateOrgPermissionInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgPermission',
      fieldName: 'createOrgPermission',
      document,
      variables,
    });
  }
  update<S extends OrgPermissionSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgPermissionPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgPermissionSelect>
  ): QueryBuilder<{
    updateOrgPermission: {
      orgPermission: InferSelectResult<OrgPermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgPermission',
      'updateOrgPermission',
      'orgPermission',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgPermissionInput',
      'id',
      'orgPermissionPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgPermission',
      fieldName: 'updateOrgPermission',
      document,
      variables,
    });
  }
  delete<S extends OrgPermissionSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgPermissionSelect>
  ): QueryBuilder<{
    deleteOrgPermission: {
      orgPermission: InferSelectResult<OrgPermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgPermission',
      'deleteOrgPermission',
      'orgPermission',
      {
        id: args.where.id,
      },
      'DeleteOrgPermissionInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgPermission',
      fieldName: 'deleteOrgPermission',
      document,
      variables,
    });
  }
}
