-- Revert: schemas/routing_public/tables/platform_domain_verifications/constraints/platform_domain_verifications_pkey/constraint


ALTER TABLE routing_public.platform_domain_verifications 
  DROP CONSTRAINT platform_domain_verifications_pkey RESTRICT;