-- Revert: schemas/routing_public/tables/platform_email_identities/indexes/platform_email_identities_provider_account_id_idx


DROP INDEX routing_public.platform_email_identities_provider_account_id_idx;