-- Revert: schemas/routing_public/tables/platform_site_deep_links/constraints/platform_site_deep_links_site_id_slug_key/constraint


ALTER TABLE routing_public.platform_site_deep_links 
  DROP CONSTRAINT platform_site_deep_links_site_id_slug_key RESTRICT;