/**
 * Warning configuration for soft limits. Each row defines a warning threshold and the job task to enqueue when usage approaches it.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appLimitWarningKeys } from '../query-keys';
import type { AppLimitWarningSelect, AppLimitWarningWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppLimitWarningSelect, AppLimitWarningWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLimitWarningQueryKey = appLimitWarningKeys.detail;
/**
 * Warning configuration for soft limits. Each row defines a warning threshold and the job task to enqueue when usage approaches it.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitWarningQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppLimitWarningQuery<
  S extends AppLimitWarningSelect,
  TData = {
    appLimitWarning: InferSelectResult<AppLimitWarningWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitWarningSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLimitWarning: InferSelectResult<AppLimitWarningWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLimitWarningQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppLimitWarningSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppLimitWarningSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLimitWarningKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitWarning.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Warning configuration for soft limits. Each row defines a warning threshold and the job task to enqueue when usage approaches it.
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitWarningQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppLimitWarningQuery<S extends AppLimitWarningSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppLimitWarningSelect>;
}): Promise<{
  appLimitWarning: InferSelectResult<AppLimitWarningWithRelations, S> | null;
}>;
export async function fetchAppLimitWarningQuery(params: {
  id: string;
  selection: SelectionConfig<AppLimitWarningSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppLimitWarningSelect>(params.selection);
  return getClient()
    .appLimitWarning.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Warning configuration for soft limits. Each row defines a warning threshold and the job task to enqueue when usage approaches it.
 *
 * @example
 * ```ts
 * await prefetchAppLimitWarningQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppLimitWarningQuery<S extends AppLimitWarningSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitWarningSelect>;
  }
): Promise<void>;
export async function prefetchAppLimitWarningQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppLimitWarningSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppLimitWarningSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appLimitWarningKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitWarning.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
