/**
 * Redeemable credit codes managed by admins with the add_credits permission
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appLimitCreditCodeKeys } from '../query-keys';
import type {
  AppLimitCreditCodeSelect,
  AppLimitCreditCodeWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  AppLimitCreditCodeSelect,
  AppLimitCreditCodeWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLimitCreditCodeQueryKey = appLimitCreditCodeKeys.detail;
/**
 * Redeemable credit codes managed by admins with the add_credits permission
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitCreditCodeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppLimitCreditCodeQuery<
  S extends AppLimitCreditCodeSelect,
  TData = {
    appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitCreditCodeSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLimitCreditCodeQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppLimitCreditCodeSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppLimitCreditCodeSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLimitCreditCodeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitCreditCode.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Redeemable credit codes managed by admins with the add_credits permission
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitCreditCodeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppLimitCreditCodeQuery<S extends AppLimitCreditCodeSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppLimitCreditCodeSelect>;
}): Promise<{
  appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S> | null;
}>;
export async function fetchAppLimitCreditCodeQuery(params: {
  id: string;
  selection: SelectionConfig<AppLimitCreditCodeSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppLimitCreditCodeSelect>(params.selection);
  return getClient()
    .appLimitCreditCode.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Redeemable credit codes managed by admins with the add_credits permission
 *
 * @example
 * ```ts
 * await prefetchAppLimitCreditCodeQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppLimitCreditCodeQuery<S extends AppLimitCreditCodeSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitCreditCodeSelect>;
  }
): Promise<void>;
export async function prefetchAppLimitCreditCodeQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppLimitCreditCodeSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppLimitCreditCodeSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appLimitCreditCodeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitCreditCode.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
