/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appFileKeys } from '../query-keys';
import type { AppFileSelect, AppFileWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppFileSelect, AppFileWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appFileQueryKey = appFileKeys.detail;
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppFileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppFileQuery<
  S extends AppFileSelect,
  TData = {
    appFile: InferSelectResult<AppFileWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppFileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appFile: InferSelectResult<AppFileWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppFileQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppFileSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppFileSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appFileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appFile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * const data = await fetchAppFileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppFileQuery<S extends AppFileSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppFileSelect>;
}): Promise<{
  appFile: InferSelectResult<AppFileWithRelations, S> | null;
}>;
export async function fetchAppFileQuery(params: {
  id: string;
  selection: SelectionConfig<AppFileSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppFileSelect>(params.selection);
  return getClient()
    .appFile.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * await prefetchAppFileQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppFileQuery<S extends AppFileSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppFileSelect>;
  }
): Promise<void>;
export async function prefetchAppFileQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppFileSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppFileSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appFileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appFile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
