/**
 * Default cap values for static configuration limits (max file size, feature flags, etc.). Not metered — just read by consumers.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appLimitCapsDefaultKeys } from '../query-keys';
import type {
  AppLimitCapsDefaultSelect,
  AppLimitCapsDefaultWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  AppLimitCapsDefaultSelect,
  AppLimitCapsDefaultWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLimitCapsDefaultQueryKey = appLimitCapsDefaultKeys.detail;
/**
 * Default cap values for static configuration limits (max file size, feature flags, etc.). Not metered — just read by consumers.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitCapsDefaultQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppLimitCapsDefaultQuery<
  S extends AppLimitCapsDefaultSelect,
  TData = {
    appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitCapsDefaultSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLimitCapsDefaultQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppLimitCapsDefaultSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppLimitCapsDefaultSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLimitCapsDefaultKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitCapsDefault.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Default cap values for static configuration limits (max file size, feature flags, etc.). Not metered — just read by consumers.
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitCapsDefaultQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppLimitCapsDefaultQuery<S extends AppLimitCapsDefaultSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppLimitCapsDefaultSelect>;
}): Promise<{
  appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S> | null;
}>;
export async function fetchAppLimitCapsDefaultQuery(params: {
  id: string;
  selection: SelectionConfig<AppLimitCapsDefaultSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppLimitCapsDefaultSelect>(params.selection);
  return getClient()
    .appLimitCapsDefault.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Default cap values for static configuration limits (max file size, feature flags, etc.). Not metered — just read by consumers.
 *
 * @example
 * ```ts
 * await prefetchAppLimitCapsDefaultQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppLimitCapsDefaultQuery<S extends AppLimitCapsDefaultSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitCapsDefaultSelect>;
  }
): Promise<void>;
export async function prefetchAppLimitCapsDefaultQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppLimitCapsDefaultSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppLimitCapsDefaultSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appLimitCapsDefaultKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitCapsDefault.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
