/**
 * Partitioned append-only audit log of authentication events (sign-in, sign-up, password changes, etc.)
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { auditLogAuthKeys } from '../query-keys';
import type { AuditLogAuthSelect, AuditLogAuthWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AuditLogAuthSelect, AuditLogAuthWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const auditLogAuthQueryKey = auditLogAuthKeys.detail;
/**
 * Partitioned append-only audit log of authentication events (sign-in, sign-up, password changes, etc.)
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAuditLogAuthQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAuditLogAuthQuery<
  S extends AuditLogAuthSelect,
  TData = {
    auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AuditLogAuthSelect>;
  } & Omit<
    UseQueryOptions<
      {
        auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAuditLogAuthQuery(
  params: {
    id: string;
    selection: SelectionConfig<AuditLogAuthSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AuditLogAuthSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: auditLogAuthKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .auditLogAuth.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Partitioned append-only audit log of authentication events (sign-in, sign-up, password changes, etc.)
 *
 * @example
 * ```ts
 * const data = await fetchAuditLogAuthQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAuditLogAuthQuery<S extends AuditLogAuthSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AuditLogAuthSelect>;
}): Promise<{
  auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S> | null;
}>;
export async function fetchAuditLogAuthQuery(params: {
  id: string;
  selection: SelectionConfig<AuditLogAuthSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AuditLogAuthSelect>(params.selection);
  return getClient()
    .auditLogAuth.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Partitioned append-only audit log of authentication events (sign-in, sign-up, password changes, etc.)
 *
 * @example
 * ```ts
 * await prefetchAuditLogAuthQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAuditLogAuthQuery<S extends AuditLogAuthSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AuditLogAuthSelect>;
  }
): Promise<void>;
export async function prefetchAuditLogAuthQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AuditLogAuthSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AuditLogAuthSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: auditLogAuthKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .auditLogAuth.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
