/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appFileKeys } from '../query-keys';
import type {
  AppFileSelect,
  AppFileWithRelations,
  AppFileFilter,
  AppFileOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppFileSelect,
  AppFileWithRelations,
  AppFileFilter,
  AppFileOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appFilesQueryKey = appFileKeys.list;
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppFilesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppFilesQuery<
  S extends AppFileSelect,
  TData = {
    appFiles: ConnectionResult<InferSelectResult<AppFileWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppFileFilter, AppFileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppFileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appFiles: ConnectionResult<InferSelectResult<AppFileWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppFilesQuery(
  params: {
    selection: ListSelectionConfig<AppFileSelect, AppFileFilter, AppFileOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<AppFileSelect, AppFileFilter, AppFileOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appFileKeys.list(args),
    queryFn: () => getClient().appFile.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * const data = await fetchAppFilesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppFilesQuery<S extends AppFileSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppFileFilter, AppFileOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppFileSelect>;
}): Promise<{
  appFiles: ConnectionResult<InferSelectResult<AppFileWithRelations, S>>;
}>;
export async function fetchAppFilesQuery(params: {
  selection: ListSelectionConfig<AppFileSelect, AppFileFilter, AppFileOrderBy>;
}) {
  const args = buildListSelectionArgs<AppFileSelect, AppFileFilter, AppFileOrderBy>(
    params.selection
  );
  return getClient().appFile.findMany(args).unwrap();
}
/**
 * Individual file records within buckets, with immutable identity fields and mutable metadata
 *
 * @example
 * ```ts
 * await prefetchAppFilesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppFilesQuery<S extends AppFileSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppFileFilter, AppFileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppFileSelect>;
  }
): Promise<void>;
export async function prefetchAppFilesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppFileSelect, AppFileFilter, AppFileOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<AppFileSelect, AppFileFilter, AppFileOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: appFileKeys.list(args),
    queryFn: () => getClient().appFile.findMany(args).unwrap(),
  });
}
