/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appBucketKeys } from '../query-keys';
import type {
  AppBucketSelect,
  AppBucketWithRelations,
  AppBucketFilter,
  AppBucketOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppBucketSelect,
  AppBucketWithRelations,
  AppBucketFilter,
  AppBucketOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appBucketsQueryKey = appBucketKeys.list;
/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppBucketsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppBucketsQuery<
  S extends AppBucketSelect,
  TData = {
    appBuckets: ConnectionResult<InferSelectResult<AppBucketWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppBucketFilter, AppBucketOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppBucketSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appBuckets: ConnectionResult<InferSelectResult<AppBucketWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppBucketsQuery(
  params: {
    selection: ListSelectionConfig<AppBucketSelect, AppBucketFilter, AppBucketOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<AppBucketSelect, AppBucketFilter, AppBucketOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appBucketKeys.list(args),
    queryFn: () => getClient().appBucket.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 *
 * @example
 * ```ts
 * const data = await fetchAppBucketsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppBucketsQuery<S extends AppBucketSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppBucketFilter, AppBucketOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppBucketSelect>;
}): Promise<{
  appBuckets: ConnectionResult<InferSelectResult<AppBucketWithRelations, S>>;
}>;
export async function fetchAppBucketsQuery(params: {
  selection: ListSelectionConfig<AppBucketSelect, AppBucketFilter, AppBucketOrderBy>;
}) {
  const args = buildListSelectionArgs<AppBucketSelect, AppBucketFilter, AppBucketOrderBy>(
    params.selection
  );
  return getClient().appBucket.findMany(args).unwrap();
}
/**
 * Logical storage containers that group files with shared access policies and CDN behavior
 *
 * @example
 * ```ts
 * await prefetchAppBucketsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppBucketsQuery<S extends AppBucketSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppBucketFilter, AppBucketOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppBucketSelect>;
  }
): Promise<void>;
export async function prefetchAppBucketsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppBucketSelect, AppBucketFilter, AppBucketOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<AppBucketSelect, AppBucketFilter, AppBucketOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: appBucketKeys.list(args),
    queryFn: () => getClient().appBucket.findMany(args).unwrap(),
  });
}
