/**
 * Default maximum values for each named limit, applied when no per-actor override exists
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appLimitDefaultKeys } from '../query-keys';
import type { AppLimitDefaultSelect, AppLimitDefaultWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppLimitDefaultSelect, AppLimitDefaultWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLimitDefaultQueryKey = appLimitDefaultKeys.detail;
/**
 * Default maximum values for each named limit, applied when no per-actor override exists
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitDefaultQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppLimitDefaultQuery<
  S extends AppLimitDefaultSelect,
  TData = {
    appLimitDefault: InferSelectResult<AppLimitDefaultWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitDefaultSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLimitDefault: InferSelectResult<AppLimitDefaultWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLimitDefaultQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppLimitDefaultSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppLimitDefaultSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLimitDefaultKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitDefault.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Default maximum values for each named limit, applied when no per-actor override exists
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitDefaultQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppLimitDefaultQuery<S extends AppLimitDefaultSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppLimitDefaultSelect>;
}): Promise<{
  appLimitDefault: InferSelectResult<AppLimitDefaultWithRelations, S> | null;
}>;
export async function fetchAppLimitDefaultQuery(params: {
  id: string;
  selection: SelectionConfig<AppLimitDefaultSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppLimitDefaultSelect>(params.selection);
  return getClient()
    .appLimitDefault.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Default maximum values for each named limit, applied when no per-actor override exists
 *
 * @example
 * ```ts
 * await prefetchAppLimitDefaultQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppLimitDefaultQuery<S extends AppLimitDefaultSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLimitDefaultSelect>;
  }
): Promise<void>;
export async function prefetchAppLimitDefaultQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppLimitDefaultSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppLimitDefaultSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appLimitDefaultKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLimitDefault.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
