/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appPermissionKeys } from '../query-keys';
import type { AppPermissionSelect, AppPermissionWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppPermissionSelect, AppPermissionWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appPermissionQueryKey = appPermissionKeys.detail;
/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppPermissionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppPermissionQuery<
  S extends AppPermissionSelect,
  TData = {
    appPermission: InferSelectResult<AppPermissionWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppPermissionSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appPermission: InferSelectResult<AppPermissionWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppPermissionQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppPermissionSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppPermissionSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appPermissionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appPermission.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * const data = await fetchAppPermissionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppPermissionQuery<S extends AppPermissionSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppPermissionSelect>;
}): Promise<{
  appPermission: InferSelectResult<AppPermissionWithRelations, S> | null;
}>;
export async function fetchAppPermissionQuery(params: {
  id: string;
  selection: SelectionConfig<AppPermissionSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppPermissionSelect>(params.selection);
  return getClient()
    .appPermission.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * await prefetchAppPermissionQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppPermissionQuery<S extends AppPermissionSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppPermissionSelect>;
  }
): Promise<void>;
export async function prefetchAppPermissionQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppPermissionSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppPermissionSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appPermissionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appPermission.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
