/**
 * Append-only ledger of credit grants that automatically update limit ceilings
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appLimitCreditKeys } from '../query-keys';
import type {
  AppLimitCreditSelect,
  AppLimitCreditWithRelations,
  AppLimitCreditFilter,
  AppLimitCreditOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppLimitCreditSelect,
  AppLimitCreditWithRelations,
  AppLimitCreditFilter,
  AppLimitCreditOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLimitCreditsQueryKey = appLimitCreditKeys.list;
/**
 * Append-only ledger of credit grants that automatically update limit ceilings
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitCreditsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppLimitCreditsQuery<
  S extends AppLimitCreditSelect,
  TData = {
    appLimitCredits: ConnectionResult<InferSelectResult<AppLimitCreditWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppLimitCreditFilter, AppLimitCreditOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppLimitCreditSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLimitCredits: ConnectionResult<InferSelectResult<AppLimitCreditWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLimitCreditsQuery(
  params: {
    selection: ListSelectionConfig<
      AppLimitCreditSelect,
      AppLimitCreditFilter,
      AppLimitCreditOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    AppLimitCreditSelect,
    AppLimitCreditFilter,
    AppLimitCreditOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLimitCreditKeys.list(args),
    queryFn: () => getClient().appLimitCredit.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Append-only ledger of credit grants that automatically update limit ceilings
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitCreditsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppLimitCreditsQuery<S extends AppLimitCreditSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppLimitCreditFilter, AppLimitCreditOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppLimitCreditSelect>;
}): Promise<{
  appLimitCredits: ConnectionResult<InferSelectResult<AppLimitCreditWithRelations, S>>;
}>;
export async function fetchAppLimitCreditsQuery(params: {
  selection: ListSelectionConfig<AppLimitCreditSelect, AppLimitCreditFilter, AppLimitCreditOrderBy>;
}) {
  const args = buildListSelectionArgs<
    AppLimitCreditSelect,
    AppLimitCreditFilter,
    AppLimitCreditOrderBy
  >(params.selection);
  return getClient().appLimitCredit.findMany(args).unwrap();
}
/**
 * Append-only ledger of credit grants that automatically update limit ceilings
 *
 * @example
 * ```ts
 * await prefetchAppLimitCreditsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppLimitCreditsQuery<S extends AppLimitCreditSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppLimitCreditFilter, AppLimitCreditOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppLimitCreditSelect>;
  }
): Promise<void>;
export async function prefetchAppLimitCreditsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      AppLimitCreditSelect,
      AppLimitCreditFilter,
      AppLimitCreditOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    AppLimitCreditSelect,
    AppLimitCreditFilter,
    AppLimitCreditOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appLimitCreditKeys.list(args),
    queryFn: () => getClient().appLimitCredit.findMany(args).unwrap(),
  });
}
