/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appLimitCapKeys } from '../query-keys';
import type {
  AppLimitCapSelect,
  AppLimitCapWithRelations,
  AppLimitCapFilter,
  AppLimitCapOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppLimitCapSelect,
  AppLimitCapWithRelations,
  AppLimitCapFilter,
  AppLimitCapOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLimitCapsQueryKey = appLimitCapKeys.list;
/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLimitCapsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppLimitCapsQuery<
  S extends AppLimitCapSelect,
  TData = {
    appLimitCaps: ConnectionResult<InferSelectResult<AppLimitCapWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppLimitCapFilter, AppLimitCapOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppLimitCapSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLimitCaps: ConnectionResult<InferSelectResult<AppLimitCapWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLimitCapsQuery(
  params: {
    selection: ListSelectionConfig<AppLimitCapSelect, AppLimitCapFilter, AppLimitCapOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<AppLimitCapSelect, AppLimitCapFilter, AppLimitCapOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLimitCapKeys.list(args),
    queryFn: () => getClient().appLimitCap.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 *
 * @example
 * ```ts
 * const data = await fetchAppLimitCapsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppLimitCapsQuery<S extends AppLimitCapSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppLimitCapFilter, AppLimitCapOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppLimitCapSelect>;
}): Promise<{
  appLimitCaps: ConnectionResult<InferSelectResult<AppLimitCapWithRelations, S>>;
}>;
export async function fetchAppLimitCapsQuery(params: {
  selection: ListSelectionConfig<AppLimitCapSelect, AppLimitCapFilter, AppLimitCapOrderBy>;
}) {
  const args = buildListSelectionArgs<AppLimitCapSelect, AppLimitCapFilter, AppLimitCapOrderBy>(
    params.selection
  );
  return getClient().appLimitCap.findMany(args).unwrap();
}
/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 *
 * @example
 * ```ts
 * await prefetchAppLimitCapsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppLimitCapsQuery<S extends AppLimitCapSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppLimitCapFilter, AppLimitCapOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppLimitCapSelect>;
  }
): Promise<void>;
export async function prefetchAppLimitCapsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppLimitCapSelect, AppLimitCapFilter, AppLimitCapOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<AppLimitCapSelect, AppLimitCapFilter, AppLimitCapOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: appLimitCapKeys.list(args),
    queryFn: () => getClient().appLimitCap.findMany(args).unwrap(),
  });
}
