/**
 * List query hook for IdentityProvider
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { identityProviderKeys } from '../query-keys';
import type {
  IdentityProviderSelect,
  IdentityProviderWithRelations,
  IdentityProviderFilter,
  IdentityProviderOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  IdentityProviderSelect,
  IdentityProviderWithRelations,
  IdentityProviderFilter,
  IdentityProviderOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const identityProvidersQueryKey = identityProviderKeys.list;
/**
 * Query hook for fetching IdentityProvider list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useIdentityProvidersQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useIdentityProvidersQuery<
  S extends IdentityProviderSelect,
  TData = {
    identityProviders: ConnectionResult<InferSelectResult<IdentityProviderWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, IdentityProviderFilter, IdentityProviderOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, IdentityProviderSelect>;
  } & Omit<
    UseQueryOptions<
      {
        identityProviders: ConnectionResult<InferSelectResult<IdentityProviderWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useIdentityProvidersQuery(
  params: {
    selection: ListSelectionConfig<
      IdentityProviderSelect,
      IdentityProviderFilter,
      IdentityProviderOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    IdentityProviderSelect,
    IdentityProviderFilter,
    IdentityProviderOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: identityProviderKeys.list(args),
    queryFn: () => getClient().identityProvider.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch IdentityProvider list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchIdentityProvidersQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchIdentityProvidersQuery<S extends IdentityProviderSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, IdentityProviderFilter, IdentityProviderOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, IdentityProviderSelect>;
}): Promise<{
  identityProviders: ConnectionResult<InferSelectResult<IdentityProviderWithRelations, S>>;
}>;
export async function fetchIdentityProvidersQuery(params: {
  selection: ListSelectionConfig<
    IdentityProviderSelect,
    IdentityProviderFilter,
    IdentityProviderOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    IdentityProviderSelect,
    IdentityProviderFilter,
    IdentityProviderOrderBy
  >(params.selection);
  return getClient().identityProvider.findMany(args).unwrap();
}
/**
 * Prefetch IdentityProvider list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchIdentityProvidersQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchIdentityProvidersQuery<S extends IdentityProviderSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, IdentityProviderFilter, IdentityProviderOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, IdentityProviderSelect>;
  }
): Promise<void>;
export async function prefetchIdentityProvidersQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      IdentityProviderSelect,
      IdentityProviderFilter,
      IdentityProviderOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    IdentityProviderSelect,
    IdentityProviderFilter,
    IdentityProviderOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: identityProviderKeys.list(args),
    queryFn: () => getClient().identityProvider.findMany(args).unwrap(),
  });
}
