/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgLimitCapKeys } from '../query-keys';
import type {
  OrgLimitCapSelect,
  OrgLimitCapWithRelations,
  OrgLimitCapFilter,
  OrgLimitCapOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgLimitCapSelect,
  OrgLimitCapWithRelations,
  OrgLimitCapFilter,
  OrgLimitCapOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgLimitCapsQueryKey = orgLimitCapKeys.list;
/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgLimitCapsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgLimitCapsQuery<
  S extends OrgLimitCapSelect,
  TData = {
    orgLimitCaps: ConnectionResult<InferSelectResult<OrgLimitCapWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgLimitCapFilter, OrgLimitCapOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgLimitCapSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgLimitCaps: ConnectionResult<InferSelectResult<OrgLimitCapWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgLimitCapsQuery(
  params: {
    selection: ListSelectionConfig<OrgLimitCapSelect, OrgLimitCapFilter, OrgLimitCapOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<OrgLimitCapSelect, OrgLimitCapFilter, OrgLimitCapOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgLimitCapKeys.list(args),
    queryFn: () => getClient().orgLimitCap.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 *
 * @example
 * ```ts
 * const data = await fetchOrgLimitCapsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgLimitCapsQuery<S extends OrgLimitCapSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgLimitCapFilter, OrgLimitCapOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgLimitCapSelect>;
}): Promise<{
  orgLimitCaps: ConnectionResult<InferSelectResult<OrgLimitCapWithRelations, S>>;
}>;
export async function fetchOrgLimitCapsQuery(params: {
  selection: ListSelectionConfig<OrgLimitCapSelect, OrgLimitCapFilter, OrgLimitCapOrderBy>;
}) {
  const args = buildListSelectionArgs<OrgLimitCapSelect, OrgLimitCapFilter, OrgLimitCapOrderBy>(
    params.selection
  );
  return getClient().orgLimitCap.findMany(args).unwrap();
}
/**
 * Per-entity cap overrides. Allows specific orgs/entities to have different cap values than the scope default.
 *
 * @example
 * ```ts
 * await prefetchOrgLimitCapsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgLimitCapsQuery<S extends OrgLimitCapSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgLimitCapFilter, OrgLimitCapOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgLimitCapSelect>;
  }
): Promise<void>;
export async function prefetchOrgLimitCapsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgLimitCapSelect, OrgLimitCapFilter, OrgLimitCapOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<OrgLimitCapSelect, OrgLimitCapFilter, OrgLimitCapOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: orgLimitCapKeys.list(args),
    queryFn: () => getClient().orgLimitCap.findMany(args).unwrap(),
  });
}
