/**
 * Per-entity settings for the memberships module
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgMembershipSettingKeys } from '../query-keys';
import type {
  OrgMembershipSettingSelect,
  OrgMembershipSettingWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  OrgMembershipSettingSelect,
  OrgMembershipSettingWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgMembershipSettingQueryKey = orgMembershipSettingKeys.detail;
/**
 * Per-entity settings for the memberships module
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipSettingQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgMembershipSettingQuery<
  S extends OrgMembershipSettingSelect,
  TData = {
    orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgMembershipSettingSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgMembershipSettingQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgMembershipSettingSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgMembershipSettingSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgMembershipSettingKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgMembershipSetting.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Per-entity settings for the memberships module
 *
 * @example
 * ```ts
 * const data = await fetchOrgMembershipSettingQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgMembershipSettingQuery<S extends OrgMembershipSettingSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgMembershipSettingSelect>;
}): Promise<{
  orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S> | null;
}>;
export async function fetchOrgMembershipSettingQuery(params: {
  id: string;
  selection: SelectionConfig<OrgMembershipSettingSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgMembershipSettingSelect>(params.selection);
  return getClient()
    .orgMembershipSetting.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Per-entity settings for the memberships module
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipSettingQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgMembershipSettingQuery<S extends OrgMembershipSettingSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgMembershipSettingSelect>;
  }
): Promise<void>;
export async function prefetchOrgMembershipSettingQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgMembershipSettingSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgMembershipSettingSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgMembershipSettingKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgMembershipSetting.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
