/**
 * Every profile a membership holds; memberships.profile_id points at one of them
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgMembershipProfileKeys } from '../query-keys';
import type {
  OrgMembershipProfileSelect,
  OrgMembershipProfileWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  OrgMembershipProfileSelect,
  OrgMembershipProfileWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgMembershipProfileQueryKey = orgMembershipProfileKeys.detail;
/**
 * Every profile a membership holds; memberships.profile_id points at one of them
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipProfileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgMembershipProfileQuery<
  S extends OrgMembershipProfileSelect,
  TData = {
    orgMembershipProfile: InferSelectResult<OrgMembershipProfileWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgMembershipProfileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgMembershipProfile: InferSelectResult<OrgMembershipProfileWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgMembershipProfileQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgMembershipProfileSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgMembershipProfileSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgMembershipProfileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgMembershipProfile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Every profile a membership holds; memberships.profile_id points at one of them
 *
 * @example
 * ```ts
 * const data = await fetchOrgMembershipProfileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgMembershipProfileQuery<S extends OrgMembershipProfileSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgMembershipProfileSelect>;
}): Promise<{
  orgMembershipProfile: InferSelectResult<OrgMembershipProfileWithRelations, S> | null;
}>;
export async function fetchOrgMembershipProfileQuery(params: {
  id: string;
  selection: SelectionConfig<OrgMembershipProfileSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgMembershipProfileSelect>(params.selection);
  return getClient()
    .orgMembershipProfile.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Every profile a membership holds; memberships.profile_id points at one of them
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipProfileQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgMembershipProfileQuery<S extends OrgMembershipProfileSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgMembershipProfileSelect>;
  }
): Promise<void>;
export async function prefetchOrgMembershipProfileQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgMembershipProfileSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgMembershipProfileSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgMembershipProfileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgMembershipProfile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
