/**
 * Append-only log of limit events for historical reporting and audit
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgLimitEventKeys } from '../query-keys';
import type { OrgLimitEventSelect, OrgLimitEventWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { OrgLimitEventSelect, OrgLimitEventWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgLimitEventQueryKey = orgLimitEventKeys.detail;
/**
 * Append-only log of limit events for historical reporting and audit
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgLimitEventQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgLimitEventQuery<
  S extends OrgLimitEventSelect,
  TData = {
    orgLimitEvent: InferSelectResult<OrgLimitEventWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgLimitEventSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgLimitEvent: InferSelectResult<OrgLimitEventWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgLimitEventQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgLimitEventSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgLimitEventSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgLimitEventKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgLimitEvent.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Append-only log of limit events for historical reporting and audit
 *
 * @example
 * ```ts
 * const data = await fetchOrgLimitEventQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgLimitEventQuery<S extends OrgLimitEventSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgLimitEventSelect>;
}): Promise<{
  orgLimitEvent: InferSelectResult<OrgLimitEventWithRelations, S> | null;
}>;
export async function fetchOrgLimitEventQuery(params: {
  id: string;
  selection: SelectionConfig<OrgLimitEventSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgLimitEventSelect>(params.selection);
  return getClient()
    .orgLimitEvent.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Append-only log of limit events for historical reporting and audit
 *
 * @example
 * ```ts
 * await prefetchOrgLimitEventQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgLimitEventQuery<S extends OrgLimitEventSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgLimitEventSelect>;
  }
): Promise<void>;
export async function prefetchOrgLimitEventQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgLimitEventSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgLimitEventSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgLimitEventKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgLimitEvent.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
