/**
 * Per-entity settings for the memberships module
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgMembershipSettingKeys } from '../query-keys';
import type {
  OrgMembershipSettingSelect,
  OrgMembershipSettingWithRelations,
  OrgMembershipSettingFilter,
  OrgMembershipSettingOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgMembershipSettingSelect,
  OrgMembershipSettingWithRelations,
  OrgMembershipSettingFilter,
  OrgMembershipSettingOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgMembershipSettingsQueryKey = orgMembershipSettingKeys.list;
/**
 * Per-entity settings for the memberships module
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipSettingsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgMembershipSettingsQuery<
  S extends OrgMembershipSettingSelect,
  TData = {
    orgMembershipSettings: ConnectionResult<
      InferSelectResult<OrgMembershipSettingWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, OrgMembershipSettingFilter, OrgMembershipSettingOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgMembershipSettingSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgMembershipSettings: ConnectionResult<
          InferSelectResult<OrgMembershipSettingWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgMembershipSettingsQuery(
  params: {
    selection: ListSelectionConfig<
      OrgMembershipSettingSelect,
      OrgMembershipSettingFilter,
      OrgMembershipSettingOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgMembershipSettingSelect,
    OrgMembershipSettingFilter,
    OrgMembershipSettingOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgMembershipSettingKeys.list(args),
    queryFn: () => getClient().orgMembershipSetting.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Per-entity settings for the memberships module
 *
 * @example
 * ```ts
 * const data = await fetchOrgMembershipSettingsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgMembershipSettingsQuery<
  S extends OrgMembershipSettingSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, OrgMembershipSettingFilter, OrgMembershipSettingOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, OrgMembershipSettingSelect>;
}): Promise<{
  orgMembershipSettings: ConnectionResult<InferSelectResult<OrgMembershipSettingWithRelations, S>>;
}>;
export async function fetchOrgMembershipSettingsQuery(params: {
  selection: ListSelectionConfig<
    OrgMembershipSettingSelect,
    OrgMembershipSettingFilter,
    OrgMembershipSettingOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    OrgMembershipSettingSelect,
    OrgMembershipSettingFilter,
    OrgMembershipSettingOrderBy
  >(params.selection);
  return getClient().orgMembershipSetting.findMany(args).unwrap();
}
/**
 * Per-entity settings for the memberships module
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipSettingsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgMembershipSettingsQuery<S extends OrgMembershipSettingSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, OrgMembershipSettingFilter, OrgMembershipSettingOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgMembershipSettingSelect>;
  }
): Promise<void>;
export async function prefetchOrgMembershipSettingsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      OrgMembershipSettingSelect,
      OrgMembershipSettingFilter,
      OrgMembershipSettingOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgMembershipSettingSelect,
    OrgMembershipSettingFilter,
    OrgMembershipSettingOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgMembershipSettingKeys.list(args),
    queryFn: () => getClient().orgMembershipSetting.findMany(args).unwrap(),
  });
}
