/**
 * List query hook for OrgGetManagersRecord
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgGetManagersRecordKeys } from '../query-keys';
import type {
  OrgGetManagersRecordSelect,
  OrgGetManagersRecordWithRelations,
  OrgGetManagersRecordFilter,
  OrgGetManagersRecordsOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgGetManagersRecordSelect,
  OrgGetManagersRecordWithRelations,
  OrgGetManagersRecordFilter,
  OrgGetManagersRecordsOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgGetManagersQueryKey = orgGetManagersRecordKeys.list;
/**
 * Query hook for fetching OrgGetManagersRecord list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgGetManagersQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgGetManagersQuery<
  S extends OrgGetManagersRecordSelect,
  TData = {
    orgGetManagers: ConnectionResult<InferSelectResult<OrgGetManagersRecordWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, OrgGetManagersRecordFilter, OrgGetManagersRecordsOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgGetManagersRecordSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgGetManagers: ConnectionResult<InferSelectResult<OrgGetManagersRecordWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgGetManagersQuery(
  params: {
    selection: ListSelectionConfig<
      OrgGetManagersRecordSelect,
      OrgGetManagersRecordFilter,
      OrgGetManagersRecordsOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgGetManagersRecordSelect,
    OrgGetManagersRecordFilter,
    OrgGetManagersRecordsOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgGetManagersRecordKeys.list(args),
    queryFn: () => getClient().orgGetManagersRecord.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch OrgGetManagersRecord list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgGetManagersQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgGetManagersQuery<S extends OrgGetManagersRecordSelect>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, OrgGetManagersRecordFilter, OrgGetManagersRecordsOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, OrgGetManagersRecordSelect>;
}): Promise<{
  orgGetManagers: ConnectionResult<InferSelectResult<OrgGetManagersRecordWithRelations, S>>;
}>;
export async function fetchOrgGetManagersQuery(params: {
  selection: ListSelectionConfig<
    OrgGetManagersRecordSelect,
    OrgGetManagersRecordFilter,
    OrgGetManagersRecordsOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    OrgGetManagersRecordSelect,
    OrgGetManagersRecordFilter,
    OrgGetManagersRecordsOrderBy
  >(params.selection);
  return getClient().orgGetManagersRecord.findMany(args).unwrap();
}
/**
 * Prefetch OrgGetManagersRecord list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgGetManagersQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgGetManagersQuery<S extends OrgGetManagersRecordSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, OrgGetManagersRecordFilter, OrgGetManagersRecordsOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgGetManagersRecordSelect>;
  }
): Promise<void>;
export async function prefetchOrgGetManagersQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      OrgGetManagersRecordSelect,
      OrgGetManagersRecordFilter,
      OrgGetManagersRecordsOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgGetManagersRecordSelect,
    OrgGetManagersRecordFilter,
    OrgGetManagersRecordsOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgGetManagersRecordKeys.list(args),
    queryFn: () => getClient().orgGetManagersRecord.findMany(args).unwrap(),
  });
}
