/**
 * List query hook for OrgApiKeyList
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgApiKeyListKeys } from '../query-keys';
import type {
  OrgApiKeyListSelect,
  OrgApiKeyListWithRelations,
  OrgApiKeyListFilter,
  OrgApiKeyListOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgApiKeyListSelect,
  OrgApiKeyListWithRelations,
  OrgApiKeyListFilter,
  OrgApiKeyListOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgApiKeyListsQueryKey = orgApiKeyListKeys.list;
/**
 * Query hook for fetching OrgApiKeyList list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgApiKeyListsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgApiKeyListsQuery<
  S extends OrgApiKeyListSelect,
  TData = {
    orgApiKeyLists: ConnectionResult<InferSelectResult<OrgApiKeyListWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgApiKeyListFilter, OrgApiKeyListOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgApiKeyListSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgApiKeyLists: ConnectionResult<InferSelectResult<OrgApiKeyListWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgApiKeyListsQuery(
  params: {
    selection: ListSelectionConfig<OrgApiKeyListSelect, OrgApiKeyListFilter, OrgApiKeyListOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgApiKeyListSelect,
    OrgApiKeyListFilter,
    OrgApiKeyListOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgApiKeyListKeys.list(args),
    queryFn: () => getClient().orgApiKeyList.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch OrgApiKeyList list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgApiKeyListsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgApiKeyListsQuery<S extends OrgApiKeyListSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgApiKeyListFilter, OrgApiKeyListOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgApiKeyListSelect>;
}): Promise<{
  orgApiKeyLists: ConnectionResult<InferSelectResult<OrgApiKeyListWithRelations, S>>;
}>;
export async function fetchOrgApiKeyListsQuery(params: {
  selection: ListSelectionConfig<OrgApiKeyListSelect, OrgApiKeyListFilter, OrgApiKeyListOrderBy>;
}) {
  const args = buildListSelectionArgs<
    OrgApiKeyListSelect,
    OrgApiKeyListFilter,
    OrgApiKeyListOrderBy
  >(params.selection);
  return getClient().orgApiKeyList.findMany(args).unwrap();
}
/**
 * Prefetch OrgApiKeyList list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgApiKeyListsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgApiKeyListsQuery<S extends OrgApiKeyListSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgApiKeyListFilter, OrgApiKeyListOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgApiKeyListSelect>;
  }
): Promise<void>;
export async function prefetchOrgApiKeyListsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgApiKeyListSelect, OrgApiKeyListFilter, OrgApiKeyListOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgApiKeyListSelect,
    OrgApiKeyListFilter,
    OrgApiKeyListOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgApiKeyListKeys.list(args),
    queryFn: () => getClient().orgApiKeyList.findMany(args).unwrap(),
  });
}
