/**
 * Single item query hook for User
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { userKeys } from '../query-keys';
import type { UserSelect, UserWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { UserSelect, UserWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const userQueryKey = userKeys.detail;
/**
 * Query hook for fetching a single User
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUserQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useUserQuery<
  S extends UserSelect,
  TData = {
    user: InferSelectResult<UserWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, UserSelect>;
  } & Omit<
    UseQueryOptions<
      {
        user: InferSelectResult<UserWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useUserQuery(
  params: {
    id: string;
    selection: SelectionConfig<UserSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<UserSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: userKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .user.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single User without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchUserQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchUserQuery<S extends UserSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, UserSelect>;
}): Promise<{
  user: InferSelectResult<UserWithRelations, S> | null;
}>;
export async function fetchUserQuery(params: {
  id: string;
  selection: SelectionConfig<UserSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<UserSelect>(params.selection);
  return getClient()
    .user.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single User for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchUserQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchUserQuery<S extends UserSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, UserSelect>;
  }
): Promise<void>;
export async function prefetchUserQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<UserSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<UserSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: userKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .user.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
