-- Revert: schemas/myapp_user_identifiers_public/tables/webauthn_credentials/indexes/webauthn_credentials_created_at_idx


DROP INDEX myapp_user_identifiers_public.webauthn_credentials_created_at_idx;


