-- Verify: schemas/routing_public/tables/platform_domain_verifications/indexes/platform_domain_verifications_created_at_idx


SELECT verify_index('routing_public.platform_domain_verifications', 'platform_domain_verifications_created_at_idx');