/**
 * Cache invalidation helpers
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

// ============================================================================
// Type-safe cache invalidation utilities
//
// Features:
// - Simple invalidation helpers per entity
// - Cascade invalidation for parent-child relationships
// - Remove helpers for delete operations
// ============================================================================

import type { QueryClient } from '@tanstack/react-query';
import {
  orgGetManagersRecordKeys,
  orgGetSubordinatesRecordKeys,
  appPermissionKeys,
  appPermissionDefaultGrantKeys,
  appProfilePermissionKeys,
  appMembershipKeys,
  appProfileGrantKeys,
  appProfileDefinitionGrantKeys,
  appInviteKeys,
  orgPermissionKeys,
  orgPermissionDefaultPermissionKeys,
  orgPermissionDefaultGrantKeys,
  orgProfilePermissionKeys,
  orgMembershipKeys,
  orgProfileGrantKeys,
  orgProfileDefinitionGrantKeys,
  orgInviteKeys,
  orgMemberKeys,
  appPermissionDefaultKeys,
  orgPermissionDefaultKeys,
  appPermissionDefaultPermissionKeys,
  appAdminGrantKeys,
  appOwnerGrantKeys,
  orgAdminGrantKeys,
  orgOwnerGrantKeys,
  orgChartEdgeGrantKeys,
  appClaimedInviteKeys,
  membershipTypeKeys,
  appGrantKeys,
  appMembershipDefaultKeys,
  orgMembershipDefaultKeys,
  orgClaimedInviteKeys,
  orgGrantKeys,
  orgChartEdgeKeys,
  appProfileTemplateKeys,
  orgProfileTemplateKeys,
  appProfileKeys,
  orgProfileKeys,
  orgMembershipSettingKeys,
  orgMemberProfileKeys,
} from './query-keys';
/**
// ============================================================================
// Invalidation Helpers
// ============================================================================

 * Type-safe query invalidation helpers
 * 
 * @example
 * ```ts
 * // Invalidate all user queries
 * invalidate.user.all(queryClient);
 * 
 * // Invalidate user lists
 * invalidate.user.lists(queryClient);
 * 
 * // Invalidate specific user
 * invalidate.user.detail(queryClient, userId);
 * ```
 */
export const invalidate = {
  /** Invalidate orgGetManagersRecord queries */ orgGetManagersRecord: {
    /** Invalidate all orgGetManagersRecord queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgGetManagersRecordKeys.all,
      }),
    /** Invalidate orgGetManagersRecord list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgGetManagersRecordKeys.lists(),
      }),
    /** Invalidate a specific orgGetManagersRecord */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgGetManagersRecordKeys.detail(id),
      }),
  },
  /** Invalidate orgGetSubordinatesRecord queries */ orgGetSubordinatesRecord: {
    /** Invalidate all orgGetSubordinatesRecord queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgGetSubordinatesRecordKeys.all,
      }),
    /** Invalidate orgGetSubordinatesRecord list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgGetSubordinatesRecordKeys.lists(),
      }),
    /** Invalidate a specific orgGetSubordinatesRecord */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgGetSubordinatesRecordKeys.detail(id),
      }),
  },
  /** Invalidate appPermission queries */ appPermission: {
    /** Invalidate all appPermission queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionKeys.all,
      }),
    /** Invalidate appPermission list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionKeys.lists(),
      }),
    /** Invalidate a specific appPermission */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionKeys.detail(id),
      }),
  },
  /** Invalidate appPermissionDefaultGrant queries */ appPermissionDefaultGrant: {
    /** Invalidate all appPermissionDefaultGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultGrantKeys.all,
      }),
    /** Invalidate appPermissionDefaultGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultGrantKeys.lists(),
      }),
    /** Invalidate a specific appPermissionDefaultGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultGrantKeys.detail(id),
      }),
  },
  /** Invalidate appProfilePermission queries */ appProfilePermission: {
    /** Invalidate all appProfilePermission queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfilePermissionKeys.all,
      }),
    /** Invalidate appProfilePermission list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfilePermissionKeys.lists(),
      }),
    /** Invalidate a specific appProfilePermission */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appProfilePermissionKeys.detail(id),
      }),
  },
  /** Invalidate appMembership queries */ appMembership: {
    /** Invalidate all appMembership queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appMembershipKeys.all,
      }),
    /** Invalidate appMembership list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appMembershipKeys.lists(),
      }),
    /** Invalidate a specific appMembership */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appMembershipKeys.detail(id),
      }),
  },
  /** Invalidate appProfileGrant queries */ appProfileGrant: {
    /** Invalidate all appProfileGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileGrantKeys.all,
      }),
    /** Invalidate appProfileGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileGrantKeys.lists(),
      }),
    /** Invalidate a specific appProfileGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appProfileGrantKeys.detail(id),
      }),
  },
  /** Invalidate appProfileDefinitionGrant queries */ appProfileDefinitionGrant: {
    /** Invalidate all appProfileDefinitionGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileDefinitionGrantKeys.all,
      }),
    /** Invalidate appProfileDefinitionGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileDefinitionGrantKeys.lists(),
      }),
    /** Invalidate a specific appProfileDefinitionGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appProfileDefinitionGrantKeys.detail(id),
      }),
  },
  /** Invalidate appInvite queries */ appInvite: {
    /** Invalidate all appInvite queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appInviteKeys.all,
      }),
    /** Invalidate appInvite list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appInviteKeys.lists(),
      }),
    /** Invalidate a specific appInvite */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appInviteKeys.detail(id),
      }),
  },
  /** Invalidate orgPermission queries */ orgPermission: {
    /** Invalidate all orgPermission queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionKeys.all,
      }),
    /** Invalidate orgPermission list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionKeys.lists(),
      }),
    /** Invalidate a specific orgPermission */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionKeys.detail(id),
      }),
  },
  /** Invalidate orgPermissionDefaultPermission queries */ orgPermissionDefaultPermission: {
    /** Invalidate all orgPermissionDefaultPermission queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultPermissionKeys.all,
      }),
    /** Invalidate orgPermissionDefaultPermission list queries */ lists: (
      queryClient: QueryClient
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultPermissionKeys.lists(),
      }),
    /** Invalidate a specific orgPermissionDefaultPermission */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultPermissionKeys.detail(id),
      }),
  },
  /** Invalidate orgPermissionDefaultGrant queries */ orgPermissionDefaultGrant: {
    /** Invalidate all orgPermissionDefaultGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultGrantKeys.all,
      }),
    /** Invalidate orgPermissionDefaultGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultGrantKeys.lists(),
      }),
    /** Invalidate a specific orgPermissionDefaultGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgProfilePermission queries */ orgProfilePermission: {
    /** Invalidate all orgProfilePermission queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfilePermissionKeys.all,
      }),
    /** Invalidate orgProfilePermission list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfilePermissionKeys.lists(),
      }),
    /** Invalidate a specific orgProfilePermission */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgProfilePermissionKeys.detail(id),
      }),
  },
  /** Invalidate orgMembership queries */ orgMembership: {
    /** Invalidate all orgMembership queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipKeys.all,
      }),
    /** Invalidate orgMembership list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipKeys.lists(),
      }),
    /** Invalidate a specific orgMembership */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipKeys.detail(id),
      }),
  },
  /** Invalidate orgProfileGrant queries */ orgProfileGrant: {
    /** Invalidate all orgProfileGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileGrantKeys.all,
      }),
    /** Invalidate orgProfileGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileGrantKeys.lists(),
      }),
    /** Invalidate a specific orgProfileGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgProfileDefinitionGrant queries */ orgProfileDefinitionGrant: {
    /** Invalidate all orgProfileDefinitionGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileDefinitionGrantKeys.all,
      }),
    /** Invalidate orgProfileDefinitionGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileDefinitionGrantKeys.lists(),
      }),
    /** Invalidate a specific orgProfileDefinitionGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileDefinitionGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgInvite queries */ orgInvite: {
    /** Invalidate all orgInvite queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgInviteKeys.all,
      }),
    /** Invalidate orgInvite list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgInviteKeys.lists(),
      }),
    /** Invalidate a specific orgInvite */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgInviteKeys.detail(id),
      }),
  },
  /** Invalidate orgMember queries */ orgMember: {
    /** Invalidate all orgMember queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMemberKeys.all,
      }),
    /** Invalidate orgMember list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMemberKeys.lists(),
      }),
    /** Invalidate a specific orgMember */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgMemberKeys.detail(id),
      }),
  },
  /** Invalidate appPermissionDefault queries */ appPermissionDefault: {
    /** Invalidate all appPermissionDefault queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultKeys.all,
      }),
    /** Invalidate appPermissionDefault list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultKeys.lists(),
      }),
    /** Invalidate a specific appPermissionDefault */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultKeys.detail(id),
      }),
  },
  /** Invalidate orgPermissionDefault queries */ orgPermissionDefault: {
    /** Invalidate all orgPermissionDefault queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultKeys.all,
      }),
    /** Invalidate orgPermissionDefault list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultKeys.lists(),
      }),
    /** Invalidate a specific orgPermissionDefault */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgPermissionDefaultKeys.detail(id),
      }),
  },
  /** Invalidate appPermissionDefaultPermission queries */ appPermissionDefaultPermission: {
    /** Invalidate all appPermissionDefaultPermission queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultPermissionKeys.all,
      }),
    /** Invalidate appPermissionDefaultPermission list queries */ lists: (
      queryClient: QueryClient
    ) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultPermissionKeys.lists(),
      }),
    /** Invalidate a specific appPermissionDefaultPermission */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appPermissionDefaultPermissionKeys.detail(id),
      }),
  },
  /** Invalidate appAdminGrant queries */ appAdminGrant: {
    /** Invalidate all appAdminGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appAdminGrantKeys.all,
      }),
    /** Invalidate appAdminGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appAdminGrantKeys.lists(),
      }),
    /** Invalidate a specific appAdminGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appAdminGrantKeys.detail(id),
      }),
  },
  /** Invalidate appOwnerGrant queries */ appOwnerGrant: {
    /** Invalidate all appOwnerGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appOwnerGrantKeys.all,
      }),
    /** Invalidate appOwnerGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appOwnerGrantKeys.lists(),
      }),
    /** Invalidate a specific appOwnerGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appOwnerGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgAdminGrant queries */ orgAdminGrant: {
    /** Invalidate all orgAdminGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgAdminGrantKeys.all,
      }),
    /** Invalidate orgAdminGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgAdminGrantKeys.lists(),
      }),
    /** Invalidate a specific orgAdminGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgAdminGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgOwnerGrant queries */ orgOwnerGrant: {
    /** Invalidate all orgOwnerGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgOwnerGrantKeys.all,
      }),
    /** Invalidate orgOwnerGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgOwnerGrantKeys.lists(),
      }),
    /** Invalidate a specific orgOwnerGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgOwnerGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgChartEdgeGrant queries */ orgChartEdgeGrant: {
    /** Invalidate all orgChartEdgeGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgChartEdgeGrantKeys.all,
      }),
    /** Invalidate orgChartEdgeGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgChartEdgeGrantKeys.lists(),
      }),
    /** Invalidate a specific orgChartEdgeGrant */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgChartEdgeGrantKeys.detail(id),
      }),
  },
  /** Invalidate appClaimedInvite queries */ appClaimedInvite: {
    /** Invalidate all appClaimedInvite queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appClaimedInviteKeys.all,
      }),
    /** Invalidate appClaimedInvite list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appClaimedInviteKeys.lists(),
      }),
    /** Invalidate a specific appClaimedInvite */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appClaimedInviteKeys.detail(id),
      }),
  },
  /** Invalidate membershipType queries */ membershipType: {
    /** Invalidate all membershipType queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: membershipTypeKeys.all,
      }),
    /** Invalidate membershipType list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: membershipTypeKeys.lists(),
      }),
    /** Invalidate a specific membershipType */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: membershipTypeKeys.detail(id),
      }),
  },
  /** Invalidate appGrant queries */ appGrant: {
    /** Invalidate all appGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appGrantKeys.all,
      }),
    /** Invalidate appGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appGrantKeys.lists(),
      }),
    /** Invalidate a specific appGrant */ detail: (queryClient: QueryClient, id: string | number) =>
      queryClient.invalidateQueries({
        queryKey: appGrantKeys.detail(id),
      }),
  },
  /** Invalidate appMembershipDefault queries */ appMembershipDefault: {
    /** Invalidate all appMembershipDefault queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appMembershipDefaultKeys.all,
      }),
    /** Invalidate appMembershipDefault list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appMembershipDefaultKeys.lists(),
      }),
    /** Invalidate a specific appMembershipDefault */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appMembershipDefaultKeys.detail(id),
      }),
  },
  /** Invalidate orgMembershipDefault queries */ orgMembershipDefault: {
    /** Invalidate all orgMembershipDefault queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipDefaultKeys.all,
      }),
    /** Invalidate orgMembershipDefault list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipDefaultKeys.lists(),
      }),
    /** Invalidate a specific orgMembershipDefault */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipDefaultKeys.detail(id),
      }),
  },
  /** Invalidate orgClaimedInvite queries */ orgClaimedInvite: {
    /** Invalidate all orgClaimedInvite queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgClaimedInviteKeys.all,
      }),
    /** Invalidate orgClaimedInvite list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgClaimedInviteKeys.lists(),
      }),
    /** Invalidate a specific orgClaimedInvite */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgClaimedInviteKeys.detail(id),
      }),
  },
  /** Invalidate orgGrant queries */ orgGrant: {
    /** Invalidate all orgGrant queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgGrantKeys.all,
      }),
    /** Invalidate orgGrant list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgGrantKeys.lists(),
      }),
    /** Invalidate a specific orgGrant */ detail: (queryClient: QueryClient, id: string | number) =>
      queryClient.invalidateQueries({
        queryKey: orgGrantKeys.detail(id),
      }),
  },
  /** Invalidate orgChartEdge queries */ orgChartEdge: {
    /** Invalidate all orgChartEdge queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgChartEdgeKeys.all,
      }),
    /** Invalidate orgChartEdge list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgChartEdgeKeys.lists(),
      }),
    /** Invalidate a specific orgChartEdge */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgChartEdgeKeys.detail(id),
      }),
  },
  /** Invalidate appProfileTemplate queries */ appProfileTemplate: {
    /** Invalidate all appProfileTemplate queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileTemplateKeys.all,
      }),
    /** Invalidate appProfileTemplate list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileTemplateKeys.lists(),
      }),
    /** Invalidate a specific appProfileTemplate */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appProfileTemplateKeys.detail(id),
      }),
  },
  /** Invalidate orgProfileTemplate queries */ orgProfileTemplate: {
    /** Invalidate all orgProfileTemplate queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileTemplateKeys.all,
      }),
    /** Invalidate orgProfileTemplate list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileTemplateKeys.lists(),
      }),
    /** Invalidate a specific orgProfileTemplate */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileTemplateKeys.detail(id),
      }),
  },
  /** Invalidate appProfile queries */ appProfile: {
    /** Invalidate all appProfile queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileKeys.all,
      }),
    /** Invalidate appProfile list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: appProfileKeys.lists(),
      }),
    /** Invalidate a specific appProfile */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: appProfileKeys.detail(id),
      }),
  },
  /** Invalidate orgProfile queries */ orgProfile: {
    /** Invalidate all orgProfile queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileKeys.all,
      }),
    /** Invalidate orgProfile list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileKeys.lists(),
      }),
    /** Invalidate a specific orgProfile */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgProfileKeys.detail(id),
      }),
  },
  /** Invalidate orgMembershipSetting queries */ orgMembershipSetting: {
    /** Invalidate all orgMembershipSetting queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipSettingKeys.all,
      }),
    /** Invalidate orgMembershipSetting list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipSettingKeys.lists(),
      }),
    /** Invalidate a specific orgMembershipSetting */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgMembershipSettingKeys.detail(id),
      }),
  },
  /** Invalidate orgMemberProfile queries */ orgMemberProfile: {
    /** Invalidate all orgMemberProfile queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMemberProfileKeys.all,
      }),
    /** Invalidate orgMemberProfile list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: orgMemberProfileKeys.lists(),
      }),
    /** Invalidate a specific orgMemberProfile */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: orgMemberProfileKeys.detail(id),
      }),
  },
} as const;
/**

// ============================================================================
// Remove Helpers (for delete operations)
// ============================================================================

 * Remove queries from cache (for delete operations)
 * 
 * Use these when an entity is deleted to remove it from cache
 * instead of just invalidating (which would trigger a refetch).
 */
export const remove = {
  /** Remove orgGetManagersRecord from cache */ orgGetManagersRecord: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgGetManagersRecordKeys.detail(id),
    });
  },
  /** Remove orgGetSubordinatesRecord from cache */ orgGetSubordinatesRecord: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgGetSubordinatesRecordKeys.detail(id),
    });
  },
  /** Remove appPermission from cache */ appPermission: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appPermissionKeys.detail(id),
    });
  },
  /** Remove appPermissionDefaultGrant from cache */ appPermissionDefaultGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appPermissionDefaultGrantKeys.detail(id),
    });
  },
  /** Remove appProfilePermission from cache */ appProfilePermission: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appProfilePermissionKeys.detail(id),
    });
  },
  /** Remove appMembership from cache */ appMembership: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appMembershipKeys.detail(id),
    });
  },
  /** Remove appProfileGrant from cache */ appProfileGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appProfileGrantKeys.detail(id),
    });
  },
  /** Remove appProfileDefinitionGrant from cache */ appProfileDefinitionGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appProfileDefinitionGrantKeys.detail(id),
    });
  },
  /** Remove appInvite from cache */ appInvite: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: appInviteKeys.detail(id),
    });
  },
  /** Remove orgPermission from cache */ orgPermission: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgPermissionKeys.detail(id),
    });
  },
  /** Remove orgPermissionDefaultPermission from cache */ orgPermissionDefaultPermission: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgPermissionDefaultPermissionKeys.detail(id),
    });
  },
  /** Remove orgPermissionDefaultGrant from cache */ orgPermissionDefaultGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgPermissionDefaultGrantKeys.detail(id),
    });
  },
  /** Remove orgProfilePermission from cache */ orgProfilePermission: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgProfilePermissionKeys.detail(id),
    });
  },
  /** Remove orgMembership from cache */ orgMembership: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgMembershipKeys.detail(id),
    });
  },
  /** Remove orgProfileGrant from cache */ orgProfileGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgProfileGrantKeys.detail(id),
    });
  },
  /** Remove orgProfileDefinitionGrant from cache */ orgProfileDefinitionGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgProfileDefinitionGrantKeys.detail(id),
    });
  },
  /** Remove orgInvite from cache */ orgInvite: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: orgInviteKeys.detail(id),
    });
  },
  /** Remove orgMember from cache */ orgMember: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: orgMemberKeys.detail(id),
    });
  },
  /** Remove appPermissionDefault from cache */ appPermissionDefault: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appPermissionDefaultKeys.detail(id),
    });
  },
  /** Remove orgPermissionDefault from cache */ orgPermissionDefault: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgPermissionDefaultKeys.detail(id),
    });
  },
  /** Remove appPermissionDefaultPermission from cache */ appPermissionDefaultPermission: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appPermissionDefaultPermissionKeys.detail(id),
    });
  },
  /** Remove appAdminGrant from cache */ appAdminGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appAdminGrantKeys.detail(id),
    });
  },
  /** Remove appOwnerGrant from cache */ appOwnerGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appOwnerGrantKeys.detail(id),
    });
  },
  /** Remove orgAdminGrant from cache */ orgAdminGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgAdminGrantKeys.detail(id),
    });
  },
  /** Remove orgOwnerGrant from cache */ orgOwnerGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgOwnerGrantKeys.detail(id),
    });
  },
  /** Remove orgChartEdgeGrant from cache */ orgChartEdgeGrant: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgChartEdgeGrantKeys.detail(id),
    });
  },
  /** Remove appClaimedInvite from cache */ appClaimedInvite: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appClaimedInviteKeys.detail(id),
    });
  },
  /** Remove membershipType from cache */ membershipType: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: membershipTypeKeys.detail(id),
    });
  },
  /** Remove appGrant from cache */ appGrant: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: appGrantKeys.detail(id),
    });
  },
  /** Remove appMembershipDefault from cache */ appMembershipDefault: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appMembershipDefaultKeys.detail(id),
    });
  },
  /** Remove orgMembershipDefault from cache */ orgMembershipDefault: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgMembershipDefaultKeys.detail(id),
    });
  },
  /** Remove orgClaimedInvite from cache */ orgClaimedInvite: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgClaimedInviteKeys.detail(id),
    });
  },
  /** Remove orgGrant from cache */ orgGrant: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: orgGrantKeys.detail(id),
    });
  },
  /** Remove orgChartEdge from cache */ orgChartEdge: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgChartEdgeKeys.detail(id),
    });
  },
  /** Remove appProfileTemplate from cache */ appProfileTemplate: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appProfileTemplateKeys.detail(id),
    });
  },
  /** Remove orgProfileTemplate from cache */ orgProfileTemplate: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgProfileTemplateKeys.detail(id),
    });
  },
  /** Remove appProfile from cache */ appProfile: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: appProfileKeys.detail(id),
    });
  },
  /** Remove orgProfile from cache */ orgProfile: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgProfileKeys.detail(id),
    });
  },
  /** Remove orgMembershipSetting from cache */ orgMembershipSetting: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgMembershipSettingKeys.detail(id),
    });
  },
  /** Remove orgMemberProfile from cache */ orgMemberProfile: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: orgMemberProfileKeys.detail(id),
    });
  },
} as const;
