-- Revert: schemas/routing_public/tables/platform_email_identities/constraints/platform_email_identities_provider_account_id_fkey/constraint


ALTER TABLE routing_public.platform_email_identities 
  DROP CONSTRAINT platform_email_identities_provider_account_id_fkey RESTRICT;