/**
 * AppLimitCapsDefault model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppLimitCapsDefault,
  AppLimitCapsDefaultWithRelations,
  AppLimitCapsDefaultSelect,
  AppLimitCapsDefaultFilter,
  AppLimitCapsDefaultOrderBy,
  CreateAppLimitCapsDefaultInput,
  UpdateAppLimitCapsDefaultInput,
  AppLimitCapsDefaultPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppLimitCapsDefaultModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppLimitCapsDefaultSelect>(
    args: FindManyArgs<S, AppLimitCapsDefaultFilter, AppLimitCapsDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitCapsDefaultSelect>
  ): QueryBuilder<{
    appLimitCapsDefaults: ConnectionResult<InferSelectResult<AppLimitCapsDefaultWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitCapsDefault',
      'appLimitCapsDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppLimitCapsDefaultFilter',
      'AppLimitCapsDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCapsDefault',
      fieldName: 'appLimitCapsDefaults',
      document,
      variables,
    });
  }
  findFirst<S extends AppLimitCapsDefaultSelect>(
    args: FindFirstArgs<S, AppLimitCapsDefaultFilter, AppLimitCapsDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitCapsDefaultSelect>
  ): QueryBuilder<{
    appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppLimitCapsDefault',
      'appLimitCapsDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppLimitCapsDefaultFilter',
      'AppLimitCapsDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCapsDefault',
      fieldName: 'appLimitCapsDefault',
      document,
      variables,
      transform: (data: {
        appLimitCapsDefaults?: {
          nodes?: InferSelectResult<AppLimitCapsDefaultWithRelations, S>[];
        };
      }) => ({
        appLimitCapsDefault: data.appLimitCapsDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppLimitCapsDefaultSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppLimitCapsDefaultSelect>
  ): QueryBuilder<{
    appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitCapsDefault',
      'appLimitCapsDefaults',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppLimitCapsDefaultFilter',
      'AppLimitCapsDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCapsDefault',
      fieldName: 'appLimitCapsDefault',
      document,
      variables,
      transform: (data: {
        appLimitCapsDefaults?: {
          nodes?: InferSelectResult<AppLimitCapsDefaultWithRelations, S>[];
        };
      }) => ({
        appLimitCapsDefault: data.appLimitCapsDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppLimitCapsDefaultSelect>(
    args: CreateArgs<S, CreateAppLimitCapsDefaultInput['appLimitCapsDefault']> & {
      select: S;
    } & StrictSelect<S, AppLimitCapsDefaultSelect>
  ): QueryBuilder<{
    createAppLimitCapsDefault: {
      appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppLimitCapsDefault',
      'createAppLimitCapsDefault',
      'appLimitCapsDefault',
      args.select,
      args.data,
      'CreateAppLimitCapsDefaultInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCapsDefault',
      fieldName: 'createAppLimitCapsDefault',
      document,
      variables,
    });
  }
  update<S extends AppLimitCapsDefaultSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppLimitCapsDefaultPatch
    > & {
      select: S;
    } & StrictSelect<S, AppLimitCapsDefaultSelect>
  ): QueryBuilder<{
    updateAppLimitCapsDefault: {
      appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppLimitCapsDefault',
      'updateAppLimitCapsDefault',
      'appLimitCapsDefault',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppLimitCapsDefaultInput',
      'id',
      'appLimitCapsDefaultPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCapsDefault',
      fieldName: 'updateAppLimitCapsDefault',
      document,
      variables,
    });
  }
  delete<S extends AppLimitCapsDefaultSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppLimitCapsDefaultSelect>
  ): QueryBuilder<{
    deleteAppLimitCapsDefault: {
      appLimitCapsDefault: InferSelectResult<AppLimitCapsDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppLimitCapsDefault',
      'deleteAppLimitCapsDefault',
      'appLimitCapsDefault',
      {
        id: args.where.id,
      },
      'DeleteAppLimitCapsDefaultInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCapsDefault',
      fieldName: 'deleteAppLimitCapsDefault',
      document,
      variables,
    });
  }
}
