/**
 * AppLimitCreditCode model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppLimitCreditCode,
  AppLimitCreditCodeWithRelations,
  AppLimitCreditCodeSelect,
  AppLimitCreditCodeFilter,
  AppLimitCreditCodeOrderBy,
  CreateAppLimitCreditCodeInput,
  UpdateAppLimitCreditCodeInput,
  AppLimitCreditCodePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppLimitCreditCodeModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppLimitCreditCodeSelect>(
    args: FindManyArgs<S, AppLimitCreditCodeFilter, AppLimitCreditCodeOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitCreditCodeSelect>
  ): QueryBuilder<{
    appLimitCreditCodes: ConnectionResult<InferSelectResult<AppLimitCreditCodeWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitCreditCode',
      'appLimitCreditCodes',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppLimitCreditCodeFilter',
      'AppLimitCreditCodeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCreditCode',
      fieldName: 'appLimitCreditCodes',
      document,
      variables,
    });
  }
  findFirst<S extends AppLimitCreditCodeSelect>(
    args: FindFirstArgs<S, AppLimitCreditCodeFilter, AppLimitCreditCodeOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitCreditCodeSelect>
  ): QueryBuilder<{
    appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppLimitCreditCode',
      'appLimitCreditCodes',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppLimitCreditCodeFilter',
      'AppLimitCreditCodeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCreditCode',
      fieldName: 'appLimitCreditCode',
      document,
      variables,
      transform: (data: {
        appLimitCreditCodes?: {
          nodes?: InferSelectResult<AppLimitCreditCodeWithRelations, S>[];
        };
      }) => ({
        appLimitCreditCode: data.appLimitCreditCodes?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppLimitCreditCodeSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppLimitCreditCodeSelect>
  ): QueryBuilder<{
    appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitCreditCode',
      'appLimitCreditCodes',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppLimitCreditCodeFilter',
      'AppLimitCreditCodeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCreditCode',
      fieldName: 'appLimitCreditCode',
      document,
      variables,
      transform: (data: {
        appLimitCreditCodes?: {
          nodes?: InferSelectResult<AppLimitCreditCodeWithRelations, S>[];
        };
      }) => ({
        appLimitCreditCode: data.appLimitCreditCodes?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppLimitCreditCodeSelect>(
    args: CreateArgs<S, CreateAppLimitCreditCodeInput['appLimitCreditCode']> & {
      select: S;
    } & StrictSelect<S, AppLimitCreditCodeSelect>
  ): QueryBuilder<{
    createAppLimitCreditCode: {
      appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppLimitCreditCode',
      'createAppLimitCreditCode',
      'appLimitCreditCode',
      args.select,
      args.data,
      'CreateAppLimitCreditCodeInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCreditCode',
      fieldName: 'createAppLimitCreditCode',
      document,
      variables,
    });
  }
  update<S extends AppLimitCreditCodeSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppLimitCreditCodePatch
    > & {
      select: S;
    } & StrictSelect<S, AppLimitCreditCodeSelect>
  ): QueryBuilder<{
    updateAppLimitCreditCode: {
      appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppLimitCreditCode',
      'updateAppLimitCreditCode',
      'appLimitCreditCode',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppLimitCreditCodeInput',
      'id',
      'appLimitCreditCodePatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCreditCode',
      fieldName: 'updateAppLimitCreditCode',
      document,
      variables,
    });
  }
  delete<S extends AppLimitCreditCodeSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppLimitCreditCodeSelect>
  ): QueryBuilder<{
    deleteAppLimitCreditCode: {
      appLimitCreditCode: InferSelectResult<AppLimitCreditCodeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppLimitCreditCode',
      'deleteAppLimitCreditCode',
      'appLimitCreditCode',
      {
        id: args.where.id,
      },
      'DeleteAppLimitCreditCodeInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCreditCode',
      fieldName: 'deleteAppLimitCreditCode',
      document,
      variables,
    });
  }
}
