/**
 * AppLimitEvent model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppLimitEvent,
  AppLimitEventWithRelations,
  AppLimitEventSelect,
  AppLimitEventFilter,
  AppLimitEventOrderBy,
  CreateAppLimitEventInput,
  UpdateAppLimitEventInput,
  AppLimitEventPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppLimitEventModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppLimitEventSelect>(
    args: FindManyArgs<S, AppLimitEventFilter, AppLimitEventOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitEventSelect>
  ): QueryBuilder<{
    appLimitEvents: ConnectionResult<InferSelectResult<AppLimitEventWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitEvent',
      'appLimitEvents',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppLimitEventFilter',
      'AppLimitEventOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitEvent',
      fieldName: 'appLimitEvents',
      document,
      variables,
    });
  }
  findFirst<S extends AppLimitEventSelect>(
    args: FindFirstArgs<S, AppLimitEventFilter, AppLimitEventOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitEventSelect>
  ): QueryBuilder<{
    appLimitEvent: InferSelectResult<AppLimitEventWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppLimitEvent',
      'appLimitEvents',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppLimitEventFilter',
      'AppLimitEventOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitEvent',
      fieldName: 'appLimitEvent',
      document,
      variables,
      transform: (data: {
        appLimitEvents?: {
          nodes?: InferSelectResult<AppLimitEventWithRelations, S>[];
        };
      }) => ({
        appLimitEvent: data.appLimitEvents?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppLimitEventSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppLimitEventSelect>
  ): QueryBuilder<{
    appLimitEvent: InferSelectResult<AppLimitEventWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitEvent',
      'appLimitEvents',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppLimitEventFilter',
      'AppLimitEventOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitEvent',
      fieldName: 'appLimitEvent',
      document,
      variables,
      transform: (data: {
        appLimitEvents?: {
          nodes?: InferSelectResult<AppLimitEventWithRelations, S>[];
        };
      }) => ({
        appLimitEvent: data.appLimitEvents?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppLimitEventSelect>(
    args: CreateArgs<S, CreateAppLimitEventInput['appLimitEvent']> & {
      select: S;
    } & StrictSelect<S, AppLimitEventSelect>
  ): QueryBuilder<{
    createAppLimitEvent: {
      appLimitEvent: InferSelectResult<AppLimitEventWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppLimitEvent',
      'createAppLimitEvent',
      'appLimitEvent',
      args.select,
      args.data,
      'CreateAppLimitEventInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitEvent',
      fieldName: 'createAppLimitEvent',
      document,
      variables,
    });
  }
  update<S extends AppLimitEventSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppLimitEventPatch
    > & {
      select: S;
    } & StrictSelect<S, AppLimitEventSelect>
  ): QueryBuilder<{
    updateAppLimitEvent: {
      appLimitEvent: InferSelectResult<AppLimitEventWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppLimitEvent',
      'updateAppLimitEvent',
      'appLimitEvent',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppLimitEventInput',
      'id',
      'appLimitEventPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitEvent',
      fieldName: 'updateAppLimitEvent',
      document,
      variables,
    });
  }
  delete<S extends AppLimitEventSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppLimitEventSelect>
  ): QueryBuilder<{
    deleteAppLimitEvent: {
      appLimitEvent: InferSelectResult<AppLimitEventWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppLimitEvent',
      'deleteAppLimitEvent',
      'appLimitEvent',
      {
        id: args.where.id,
      },
      'DeleteAppLimitEventInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitEvent',
      fieldName: 'deleteAppLimitEvent',
      document,
      variables,
    });
  }
}
