/**
 * AppLimitCreditRedemption model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppLimitCreditRedemption,
  AppLimitCreditRedemptionWithRelations,
  AppLimitCreditRedemptionSelect,
  AppLimitCreditRedemptionFilter,
  AppLimitCreditRedemptionOrderBy,
  CreateAppLimitCreditRedemptionInput,
  UpdateAppLimitCreditRedemptionInput,
  AppLimitCreditRedemptionPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppLimitCreditRedemptionModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppLimitCreditRedemptionSelect>(
    args: FindManyArgs<S, AppLimitCreditRedemptionFilter, AppLimitCreditRedemptionOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitCreditRedemptionSelect>
  ): QueryBuilder<{
    appLimitCreditRedemptions: ConnectionResult<
      InferSelectResult<AppLimitCreditRedemptionWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitCreditRedemption',
      'appLimitCreditRedemptions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppLimitCreditRedemptionFilter',
      'AppLimitCreditRedemptionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCreditRedemption',
      fieldName: 'appLimitCreditRedemptions',
      document,
      variables,
    });
  }
  findFirst<S extends AppLimitCreditRedemptionSelect>(
    args: FindFirstArgs<S, AppLimitCreditRedemptionFilter, AppLimitCreditRedemptionOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLimitCreditRedemptionSelect>
  ): QueryBuilder<{
    appLimitCreditRedemption: InferSelectResult<AppLimitCreditRedemptionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppLimitCreditRedemption',
      'appLimitCreditRedemptions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppLimitCreditRedemptionFilter',
      'AppLimitCreditRedemptionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCreditRedemption',
      fieldName: 'appLimitCreditRedemption',
      document,
      variables,
      transform: (data: {
        appLimitCreditRedemptions?: {
          nodes?: InferSelectResult<AppLimitCreditRedemptionWithRelations, S>[];
        };
      }) => ({
        appLimitCreditRedemption: data.appLimitCreditRedemptions?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppLimitCreditRedemptionSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppLimitCreditRedemptionSelect>
  ): QueryBuilder<{
    appLimitCreditRedemption: InferSelectResult<AppLimitCreditRedemptionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLimitCreditRedemption',
      'appLimitCreditRedemptions',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppLimitCreditRedemptionFilter',
      'AppLimitCreditRedemptionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLimitCreditRedemption',
      fieldName: 'appLimitCreditRedemption',
      document,
      variables,
      transform: (data: {
        appLimitCreditRedemptions?: {
          nodes?: InferSelectResult<AppLimitCreditRedemptionWithRelations, S>[];
        };
      }) => ({
        appLimitCreditRedemption: data.appLimitCreditRedemptions?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppLimitCreditRedemptionSelect>(
    args: CreateArgs<S, CreateAppLimitCreditRedemptionInput['appLimitCreditRedemption']> & {
      select: S;
    } & StrictSelect<S, AppLimitCreditRedemptionSelect>
  ): QueryBuilder<{
    createAppLimitCreditRedemption: {
      appLimitCreditRedemption: InferSelectResult<AppLimitCreditRedemptionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppLimitCreditRedemption',
      'createAppLimitCreditRedemption',
      'appLimitCreditRedemption',
      args.select,
      args.data,
      'CreateAppLimitCreditRedemptionInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCreditRedemption',
      fieldName: 'createAppLimitCreditRedemption',
      document,
      variables,
    });
  }
  update<S extends AppLimitCreditRedemptionSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppLimitCreditRedemptionPatch
    > & {
      select: S;
    } & StrictSelect<S, AppLimitCreditRedemptionSelect>
  ): QueryBuilder<{
    updateAppLimitCreditRedemption: {
      appLimitCreditRedemption: InferSelectResult<AppLimitCreditRedemptionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppLimitCreditRedemption',
      'updateAppLimitCreditRedemption',
      'appLimitCreditRedemption',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppLimitCreditRedemptionInput',
      'id',
      'appLimitCreditRedemptionPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCreditRedemption',
      fieldName: 'updateAppLimitCreditRedemption',
      document,
      variables,
    });
  }
  delete<S extends AppLimitCreditRedemptionSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppLimitCreditRedemptionSelect>
  ): QueryBuilder<{
    deleteAppLimitCreditRedemption: {
      appLimitCreditRedemption: InferSelectResult<AppLimitCreditRedemptionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppLimitCreditRedemption',
      'deleteAppLimitCreditRedemption',
      'appLimitCreditRedemption',
      {
        id: args.where.id,
      },
      'DeleteAppLimitCreditRedemptionInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLimitCreditRedemption',
      fieldName: 'deleteAppLimitCreditRedemption',
      document,
      variables,
    });
  }
}
