/**
 * AppMembershipProfile model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppMembershipProfile,
  AppMembershipProfileWithRelations,
  AppMembershipProfileSelect,
  AppMembershipProfileFilter,
  AppMembershipProfileOrderBy,
  CreateAppMembershipProfileInput,
  UpdateAppMembershipProfileInput,
  AppMembershipProfilePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppMembershipProfileModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppMembershipProfileSelect>(
    args: FindManyArgs<S, AppMembershipProfileFilter, AppMembershipProfileOrderBy> & {
      select: S;
    } & StrictSelect<S, AppMembershipProfileSelect>
  ): QueryBuilder<{
    appMembershipProfiles: ConnectionResult<
      InferSelectResult<AppMembershipProfileWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppMembershipProfile',
      'appMembershipProfiles',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppMembershipProfileFilter',
      'AppMembershipProfileOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppMembershipProfile',
      fieldName: 'appMembershipProfiles',
      document,
      variables,
    });
  }
  findFirst<S extends AppMembershipProfileSelect>(
    args: FindFirstArgs<S, AppMembershipProfileFilter, AppMembershipProfileOrderBy> & {
      select: S;
    } & StrictSelect<S, AppMembershipProfileSelect>
  ): QueryBuilder<{
    appMembershipProfile: InferSelectResult<AppMembershipProfileWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppMembershipProfile',
      'appMembershipProfiles',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppMembershipProfileFilter',
      'AppMembershipProfileOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppMembershipProfile',
      fieldName: 'appMembershipProfile',
      document,
      variables,
      transform: (data: {
        appMembershipProfiles?: {
          nodes?: InferSelectResult<AppMembershipProfileWithRelations, S>[];
        };
      }) => ({
        appMembershipProfile: data.appMembershipProfiles?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppMembershipProfileSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppMembershipProfileSelect>
  ): QueryBuilder<{
    appMembershipProfile: InferSelectResult<AppMembershipProfileWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppMembershipProfile',
      'appMembershipProfiles',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppMembershipProfileFilter',
      'AppMembershipProfileOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppMembershipProfile',
      fieldName: 'appMembershipProfile',
      document,
      variables,
      transform: (data: {
        appMembershipProfiles?: {
          nodes?: InferSelectResult<AppMembershipProfileWithRelations, S>[];
        };
      }) => ({
        appMembershipProfile: data.appMembershipProfiles?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppMembershipProfileSelect>(
    args: CreateArgs<S, CreateAppMembershipProfileInput['appMembershipProfile']> & {
      select: S;
    } & StrictSelect<S, AppMembershipProfileSelect>
  ): QueryBuilder<{
    createAppMembershipProfile: {
      appMembershipProfile: InferSelectResult<AppMembershipProfileWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppMembershipProfile',
      'createAppMembershipProfile',
      'appMembershipProfile',
      args.select,
      args.data,
      'CreateAppMembershipProfileInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppMembershipProfile',
      fieldName: 'createAppMembershipProfile',
      document,
      variables,
    });
  }
  update<S extends AppMembershipProfileSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppMembershipProfilePatch
    > & {
      select: S;
    } & StrictSelect<S, AppMembershipProfileSelect>
  ): QueryBuilder<{
    updateAppMembershipProfile: {
      appMembershipProfile: InferSelectResult<AppMembershipProfileWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppMembershipProfile',
      'updateAppMembershipProfile',
      'appMembershipProfile',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppMembershipProfileInput',
      'id',
      'appMembershipProfilePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppMembershipProfile',
      fieldName: 'updateAppMembershipProfile',
      document,
      variables,
    });
  }
  delete<S extends AppMembershipProfileSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppMembershipProfileSelect>
  ): QueryBuilder<{
    deleteAppMembershipProfile: {
      appMembershipProfile: InferSelectResult<AppMembershipProfileWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppMembershipProfile',
      'deleteAppMembershipProfile',
      'appMembershipProfile',
      {
        id: args.where.id,
      },
      'DeleteAppMembershipProfileInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppMembershipProfile',
      fieldName: 'deleteAppMembershipProfile',
      document,
      variables,
    });
  }
}
