/**
 * OrgLimitCapsDefault model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgLimitCapsDefault,
  OrgLimitCapsDefaultWithRelations,
  OrgLimitCapsDefaultSelect,
  OrgLimitCapsDefaultFilter,
  OrgLimitCapsDefaultOrderBy,
  CreateOrgLimitCapsDefaultInput,
  UpdateOrgLimitCapsDefaultInput,
  OrgLimitCapsDefaultPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgLimitCapsDefaultModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgLimitCapsDefaultSelect>(
    args: FindManyArgs<S, OrgLimitCapsDefaultFilter, OrgLimitCapsDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgLimitCapsDefaultSelect>
  ): QueryBuilder<{
    orgLimitCapsDefaults: ConnectionResult<InferSelectResult<OrgLimitCapsDefaultWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgLimitCapsDefault',
      'orgLimitCapsDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgLimitCapsDefaultFilter',
      'OrgLimitCapsDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgLimitCapsDefault',
      fieldName: 'orgLimitCapsDefaults',
      document,
      variables,
    });
  }
  findFirst<S extends OrgLimitCapsDefaultSelect>(
    args: FindFirstArgs<S, OrgLimitCapsDefaultFilter, OrgLimitCapsDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgLimitCapsDefaultSelect>
  ): QueryBuilder<{
    orgLimitCapsDefault: InferSelectResult<OrgLimitCapsDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgLimitCapsDefault',
      'orgLimitCapsDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgLimitCapsDefaultFilter',
      'OrgLimitCapsDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgLimitCapsDefault',
      fieldName: 'orgLimitCapsDefault',
      document,
      variables,
      transform: (data: {
        orgLimitCapsDefaults?: {
          nodes?: InferSelectResult<OrgLimitCapsDefaultWithRelations, S>[];
        };
      }) => ({
        orgLimitCapsDefault: data.orgLimitCapsDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgLimitCapsDefaultSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgLimitCapsDefaultSelect>
  ): QueryBuilder<{
    orgLimitCapsDefault: InferSelectResult<OrgLimitCapsDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgLimitCapsDefault',
      'orgLimitCapsDefaults',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgLimitCapsDefaultFilter',
      'OrgLimitCapsDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgLimitCapsDefault',
      fieldName: 'orgLimitCapsDefault',
      document,
      variables,
      transform: (data: {
        orgLimitCapsDefaults?: {
          nodes?: InferSelectResult<OrgLimitCapsDefaultWithRelations, S>[];
        };
      }) => ({
        orgLimitCapsDefault: data.orgLimitCapsDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgLimitCapsDefaultSelect>(
    args: CreateArgs<S, CreateOrgLimitCapsDefaultInput['orgLimitCapsDefault']> & {
      select: S;
    } & StrictSelect<S, OrgLimitCapsDefaultSelect>
  ): QueryBuilder<{
    createOrgLimitCapsDefault: {
      orgLimitCapsDefault: InferSelectResult<OrgLimitCapsDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgLimitCapsDefault',
      'createOrgLimitCapsDefault',
      'orgLimitCapsDefault',
      args.select,
      args.data,
      'CreateOrgLimitCapsDefaultInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgLimitCapsDefault',
      fieldName: 'createOrgLimitCapsDefault',
      document,
      variables,
    });
  }
  update<S extends OrgLimitCapsDefaultSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgLimitCapsDefaultPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgLimitCapsDefaultSelect>
  ): QueryBuilder<{
    updateOrgLimitCapsDefault: {
      orgLimitCapsDefault: InferSelectResult<OrgLimitCapsDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgLimitCapsDefault',
      'updateOrgLimitCapsDefault',
      'orgLimitCapsDefault',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgLimitCapsDefaultInput',
      'id',
      'orgLimitCapsDefaultPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgLimitCapsDefault',
      fieldName: 'updateOrgLimitCapsDefault',
      document,
      variables,
    });
  }
  delete<S extends OrgLimitCapsDefaultSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgLimitCapsDefaultSelect>
  ): QueryBuilder<{
    deleteOrgLimitCapsDefault: {
      orgLimitCapsDefault: InferSelectResult<OrgLimitCapsDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgLimitCapsDefault',
      'deleteOrgLimitCapsDefault',
      'orgLimitCapsDefault',
      {
        id: args.where.id,
      },
      'DeleteOrgLimitCapsDefaultInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgLimitCapsDefault',
      fieldName: 'deleteOrgLimitCapsDefault',
      document,
      variables,
    });
  }
}
