/**
 * OrgProfilePermission model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgProfilePermission,
  OrgProfilePermissionWithRelations,
  OrgProfilePermissionSelect,
  OrgProfilePermissionFilter,
  OrgProfilePermissionOrderBy,
  CreateOrgProfilePermissionInput,
  UpdateOrgProfilePermissionInput,
  OrgProfilePermissionPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgProfilePermissionModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgProfilePermissionSelect>(
    args: FindManyArgs<S, OrgProfilePermissionFilter, OrgProfilePermissionOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgProfilePermissionSelect>
  ): QueryBuilder<{
    orgProfilePermissions: ConnectionResult<
      InferSelectResult<OrgProfilePermissionWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgProfilePermission',
      'orgProfilePermissions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgProfilePermissionFilter',
      'OrgProfilePermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfilePermission',
      fieldName: 'orgProfilePermissions',
      document,
      variables,
    });
  }
  findFirst<S extends OrgProfilePermissionSelect>(
    args: FindFirstArgs<S, OrgProfilePermissionFilter, OrgProfilePermissionOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgProfilePermissionSelect>
  ): QueryBuilder<{
    orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgProfilePermission',
      'orgProfilePermissions',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgProfilePermissionFilter',
      'OrgProfilePermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfilePermission',
      fieldName: 'orgProfilePermission',
      document,
      variables,
      transform: (data: {
        orgProfilePermissions?: {
          nodes?: InferSelectResult<OrgProfilePermissionWithRelations, S>[];
        };
      }) => ({
        orgProfilePermission: data.orgProfilePermissions?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgProfilePermissionSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgProfilePermissionSelect>
  ): QueryBuilder<{
    orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgProfilePermission',
      'orgProfilePermissions',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgProfilePermissionFilter',
      'OrgProfilePermissionOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfilePermission',
      fieldName: 'orgProfilePermission',
      document,
      variables,
      transform: (data: {
        orgProfilePermissions?: {
          nodes?: InferSelectResult<OrgProfilePermissionWithRelations, S>[];
        };
      }) => ({
        orgProfilePermission: data.orgProfilePermissions?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgProfilePermissionSelect>(
    args: CreateArgs<S, CreateOrgProfilePermissionInput['orgProfilePermission']> & {
      select: S;
    } & StrictSelect<S, OrgProfilePermissionSelect>
  ): QueryBuilder<{
    createOrgProfilePermission: {
      orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgProfilePermission',
      'createOrgProfilePermission',
      'orgProfilePermission',
      args.select,
      args.data,
      'CreateOrgProfilePermissionInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfilePermission',
      fieldName: 'createOrgProfilePermission',
      document,
      variables,
    });
  }
  update<S extends OrgProfilePermissionSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgProfilePermissionPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgProfilePermissionSelect>
  ): QueryBuilder<{
    updateOrgProfilePermission: {
      orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgProfilePermission',
      'updateOrgProfilePermission',
      'orgProfilePermission',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgProfilePermissionInput',
      'id',
      'orgProfilePermissionPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfilePermission',
      fieldName: 'updateOrgProfilePermission',
      document,
      variables,
    });
  }
  delete<S extends OrgProfilePermissionSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgProfilePermissionSelect>
  ): QueryBuilder<{
    deleteOrgProfilePermission: {
      orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgProfilePermission',
      'deleteOrgProfilePermission',
      'orgProfilePermission',
      {
        id: args.where.id,
      },
      'DeleteOrgProfilePermissionInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfilePermission',
      fieldName: 'deleteOrgProfilePermission',
      document,
      variables,
    });
  }
}
