/**
 * PrincipalEntity model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PrincipalEntity,
  PrincipalEntityWithRelations,
  PrincipalEntitySelect,
  PrincipalEntityFilter,
  PrincipalEntityOrderBy,
  CreatePrincipalEntityInput,
  UpdatePrincipalEntityInput,
  PrincipalEntityPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PrincipalEntityModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PrincipalEntitySelect>(
    args: FindManyArgs<S, PrincipalEntityFilter, PrincipalEntityOrderBy> & {
      select: S;
    } & StrictSelect<S, PrincipalEntitySelect>
  ): QueryBuilder<{
    principalEntities: ConnectionResult<InferSelectResult<PrincipalEntityWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PrincipalEntity',
      'principalEntities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PrincipalEntityFilter',
      'PrincipalEntityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PrincipalEntity',
      fieldName: 'principalEntities',
      document,
      variables,
    });
  }
  findFirst<S extends PrincipalEntitySelect>(
    args: FindFirstArgs<S, PrincipalEntityFilter, PrincipalEntityOrderBy> & {
      select: S;
    } & StrictSelect<S, PrincipalEntitySelect>
  ): QueryBuilder<{
    principalEntity: InferSelectResult<PrincipalEntityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PrincipalEntity',
      'principalEntities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PrincipalEntityFilter',
      'PrincipalEntityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PrincipalEntity',
      fieldName: 'principalEntity',
      document,
      variables,
      transform: (data: {
        principalEntities?: {
          nodes?: InferSelectResult<PrincipalEntityWithRelations, S>[];
        };
      }) => ({
        principalEntity: data.principalEntities?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PrincipalEntitySelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PrincipalEntitySelect>
  ): QueryBuilder<{
    principalEntity: InferSelectResult<PrincipalEntityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PrincipalEntity',
      'principalEntities',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PrincipalEntityFilter',
      'PrincipalEntityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PrincipalEntity',
      fieldName: 'principalEntity',
      document,
      variables,
      transform: (data: {
        principalEntities?: {
          nodes?: InferSelectResult<PrincipalEntityWithRelations, S>[];
        };
      }) => ({
        principalEntity: data.principalEntities?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PrincipalEntitySelect>(
    args: CreateArgs<S, CreatePrincipalEntityInput['principalEntity']> & {
      select: S;
    } & StrictSelect<S, PrincipalEntitySelect>
  ): QueryBuilder<{
    createPrincipalEntity: {
      principalEntity: InferSelectResult<PrincipalEntityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PrincipalEntity',
      'createPrincipalEntity',
      'principalEntity',
      args.select,
      args.data,
      'CreatePrincipalEntityInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PrincipalEntity',
      fieldName: 'createPrincipalEntity',
      document,
      variables,
    });
  }
  update<S extends PrincipalEntitySelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PrincipalEntityPatch
    > & {
      select: S;
    } & StrictSelect<S, PrincipalEntitySelect>
  ): QueryBuilder<{
    updatePrincipalEntity: {
      principalEntity: InferSelectResult<PrincipalEntityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PrincipalEntity',
      'updatePrincipalEntity',
      'principalEntity',
      args.select,
      args.where.id,
      args.data,
      'UpdatePrincipalEntityInput',
      'id',
      'principalEntityPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PrincipalEntity',
      fieldName: 'updatePrincipalEntity',
      document,
      variables,
    });
  }
  delete<S extends PrincipalEntitySelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PrincipalEntitySelect>
  ): QueryBuilder<{
    deletePrincipalEntity: {
      principalEntity: InferSelectResult<PrincipalEntityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PrincipalEntity',
      'deletePrincipalEntity',
      'principalEntity',
      {
        id: args.where.id,
      },
      'DeletePrincipalEntityInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PrincipalEntity',
      fieldName: 'deletePrincipalEntity',
      document,
      variables,
    });
  }
}
