/**
 * Records of ownership transfers and grants between members
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appOwnerGrantKeys } from '../query-keys';
import type {
  AppOwnerGrantSelect,
  AppOwnerGrantWithRelations,
  AppOwnerGrantFilter,
  AppOwnerGrantOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppOwnerGrantSelect,
  AppOwnerGrantWithRelations,
  AppOwnerGrantFilter,
  AppOwnerGrantOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appOwnerGrantsQueryKey = appOwnerGrantKeys.list;
/**
 * Records of ownership transfers and grants between members
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppOwnerGrantsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppOwnerGrantsQuery<
  S extends AppOwnerGrantSelect,
  TData = {
    appOwnerGrants: ConnectionResult<InferSelectResult<AppOwnerGrantWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppOwnerGrantFilter, AppOwnerGrantOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppOwnerGrantSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appOwnerGrants: ConnectionResult<InferSelectResult<AppOwnerGrantWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppOwnerGrantsQuery(
  params: {
    selection: ListSelectionConfig<AppOwnerGrantSelect, AppOwnerGrantFilter, AppOwnerGrantOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    AppOwnerGrantSelect,
    AppOwnerGrantFilter,
    AppOwnerGrantOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appOwnerGrantKeys.list(args),
    queryFn: () => getClient().appOwnerGrant.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Records of ownership transfers and grants between members
 *
 * @example
 * ```ts
 * const data = await fetchAppOwnerGrantsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppOwnerGrantsQuery<S extends AppOwnerGrantSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppOwnerGrantFilter, AppOwnerGrantOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppOwnerGrantSelect>;
}): Promise<{
  appOwnerGrants: ConnectionResult<InferSelectResult<AppOwnerGrantWithRelations, S>>;
}>;
export async function fetchAppOwnerGrantsQuery(params: {
  selection: ListSelectionConfig<AppOwnerGrantSelect, AppOwnerGrantFilter, AppOwnerGrantOrderBy>;
}) {
  const args = buildListSelectionArgs<
    AppOwnerGrantSelect,
    AppOwnerGrantFilter,
    AppOwnerGrantOrderBy
  >(params.selection);
  return getClient().appOwnerGrant.findMany(args).unwrap();
}
/**
 * Records of ownership transfers and grants between members
 *
 * @example
 * ```ts
 * await prefetchAppOwnerGrantsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppOwnerGrantsQuery<S extends AppOwnerGrantSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppOwnerGrantFilter, AppOwnerGrantOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppOwnerGrantSelect>;
  }
): Promise<void>;
export async function prefetchAppOwnerGrantsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppOwnerGrantSelect, AppOwnerGrantFilter, AppOwnerGrantOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    AppOwnerGrantSelect,
    AppOwnerGrantFilter,
    AppOwnerGrantOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appOwnerGrantKeys.list(args),
    queryFn: () => getClient().appOwnerGrant.findMany(args).unwrap(),
  });
}
