/**
 * Custom query hook for appPermissionsGetByMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { AppPermissionsGetByMaskVariables } from '../../orm/query';
import type { AppPermissionConnection } from '../../orm/input-types';
export type { AppPermissionsGetByMaskVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const appPermissionsGetByMaskQueryKey = customQueryKeys.appPermissionsGetByMask;
/**
 * Reads and enables pagination through a set of `AppPermission`.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppPermissionsGetByMaskQuery({ variables: { mask, first, offset, after } });
 *
 * if (data?.appPermissionsGetByMask) {
 *   console.log(data.appPermissionsGetByMask);
 * }
 * ```
 */
export function useAppPermissionsGetByMaskQuery<
  TData = {
    appPermissionsGetByMask: AppPermissionConnection | null;
  },
>(
  params?: {
    variables?: AppPermissionsGetByMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        appPermissionsGetByMask: AppPermissionConnection | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppPermissionsGetByMaskQuery<
  TData = {
    appPermissionsGetByMask: AppPermissionConnection | null;
  },
>(
  params?: {
    variables?: AppPermissionsGetByMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        appPermissionsGetByMask: AppPermissionConnection | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: appPermissionsGetByMaskQueryKey(variables),
    queryFn: () => getClient().query.appPermissionsGetByMask(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch appPermissionsGetByMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppPermissionsGetByMaskQuery({ variables: { mask, first, offset, after } });
 * ```
 */
export async function fetchAppPermissionsGetByMaskQuery(params?: {
  variables?: AppPermissionsGetByMaskVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.appPermissionsGetByMask(variables).unwrap();
}
/**
 * Prefetch appPermissionsGetByMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppPermissionsGetByMaskQuery(queryClient, { variables: { mask, first, offset, after } });
 * ```
 */
export async function prefetchAppPermissionsGetByMaskQuery(
  queryClient: QueryClient,
  params?: {
    variables?: AppPermissionsGetByMaskVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: appPermissionsGetByMaskQueryKey(variables),
    queryFn: () => getClient().query.appPermissionsGetByMask(variables).unwrap(),
  });
}
