/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appInviteKeys } from '../query-keys';
import type {
  AppInviteSelect,
  AppInviteWithRelations,
  AppInviteFilter,
  AppInviteOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppInviteSelect,
  AppInviteWithRelations,
  AppInviteFilter,
  AppInviteOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appInvitesQueryKey = appInviteKeys.list;
/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppInvitesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppInvitesQuery<
  S extends AppInviteSelect,
  TData = {
    appInvites: ConnectionResult<InferSelectResult<AppInviteWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppInviteFilter, AppInviteOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppInviteSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appInvites: ConnectionResult<InferSelectResult<AppInviteWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppInvitesQuery(
  params: {
    selection: ListSelectionConfig<AppInviteSelect, AppInviteFilter, AppInviteOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<AppInviteSelect, AppInviteFilter, AppInviteOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appInviteKeys.list(args),
    queryFn: () => getClient().appInvite.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 *
 * @example
 * ```ts
 * const data = await fetchAppInvitesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppInvitesQuery<S extends AppInviteSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppInviteFilter, AppInviteOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppInviteSelect>;
}): Promise<{
  appInvites: ConnectionResult<InferSelectResult<AppInviteWithRelations, S>>;
}>;
export async function fetchAppInvitesQuery(params: {
  selection: ListSelectionConfig<AppInviteSelect, AppInviteFilter, AppInviteOrderBy>;
}) {
  const args = buildListSelectionArgs<AppInviteSelect, AppInviteFilter, AppInviteOrderBy>(
    params.selection
  );
  return getClient().appInvite.findMany(args).unwrap();
}
/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 *
 * @example
 * ```ts
 * await prefetchAppInvitesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppInvitesQuery<S extends AppInviteSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppInviteFilter, AppInviteOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppInviteSelect>;
  }
): Promise<void>;
export async function prefetchAppInvitesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppInviteSelect, AppInviteFilter, AppInviteOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<AppInviteSelect, AppInviteFilter, AppInviteOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: appInviteKeys.list(args),
    queryFn: () => getClient().appInvite.findMany(args).unwrap(),
  });
}
