/**
 * Defines the different scopes of membership (e.g. App Member, Organization Member, Group Member)
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { membershipTypeKeys } from '../query-keys';
import type { MembershipTypeSelect, MembershipTypeWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { MembershipTypeSelect, MembershipTypeWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const membershipTypeQueryKey = membershipTypeKeys.detail;
/**
 * Defines the different scopes of membership (e.g. App Member, Organization Member, Group Member)
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useMembershipTypeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useMembershipTypeQuery<
  S extends MembershipTypeSelect,
  TData = {
    membershipType: InferSelectResult<MembershipTypeWithRelations, S> | null;
  },
>(
  params: {
    id: number;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, MembershipTypeSelect>;
  } & Omit<
    UseQueryOptions<
      {
        membershipType: InferSelectResult<MembershipTypeWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useMembershipTypeQuery(
  params: {
    id: number;
    selection: SelectionConfig<MembershipTypeSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<MembershipTypeSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: membershipTypeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .membershipType.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines the different scopes of membership (e.g. App Member, Organization Member, Group Member)
 *
 * @example
 * ```ts
 * const data = await fetchMembershipTypeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchMembershipTypeQuery<S extends MembershipTypeSelect>(params: {
  id: number;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, MembershipTypeSelect>;
}): Promise<{
  membershipType: InferSelectResult<MembershipTypeWithRelations, S> | null;
}>;
export async function fetchMembershipTypeQuery(params: {
  id: number;
  selection: SelectionConfig<MembershipTypeSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<MembershipTypeSelect>(params.selection);
  return getClient()
    .membershipType.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Defines the different scopes of membership (e.g. App Member, Organization Member, Group Member)
 *
 * @example
 * ```ts
 * await prefetchMembershipTypeQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchMembershipTypeQuery<S extends MembershipTypeSelect>(
  queryClient: QueryClient,
  params: {
    id: number;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, MembershipTypeSelect>;
  }
): Promise<void>;
export async function prefetchMembershipTypeQuery(
  queryClient: QueryClient,
  params: {
    id: number;
    selection: SelectionConfig<MembershipTypeSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<MembershipTypeSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: membershipTypeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .membershipType.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
