/**
 * Records of ownership transfers and grants between members
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgOwnerGrantKeys } from '../query-keys';
import type {
  OrgOwnerGrantSelect,
  OrgOwnerGrantWithRelations,
  OrgOwnerGrantFilter,
  OrgOwnerGrantOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgOwnerGrantSelect,
  OrgOwnerGrantWithRelations,
  OrgOwnerGrantFilter,
  OrgOwnerGrantOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgOwnerGrantsQueryKey = orgOwnerGrantKeys.list;
/**
 * Records of ownership transfers and grants between members
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgOwnerGrantsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgOwnerGrantsQuery<
  S extends OrgOwnerGrantSelect,
  TData = {
    orgOwnerGrants: ConnectionResult<InferSelectResult<OrgOwnerGrantWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgOwnerGrantFilter, OrgOwnerGrantOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgOwnerGrantSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgOwnerGrants: ConnectionResult<InferSelectResult<OrgOwnerGrantWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgOwnerGrantsQuery(
  params: {
    selection: ListSelectionConfig<OrgOwnerGrantSelect, OrgOwnerGrantFilter, OrgOwnerGrantOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgOwnerGrantSelect,
    OrgOwnerGrantFilter,
    OrgOwnerGrantOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgOwnerGrantKeys.list(args),
    queryFn: () => getClient().orgOwnerGrant.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Records of ownership transfers and grants between members
 *
 * @example
 * ```ts
 * const data = await fetchOrgOwnerGrantsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgOwnerGrantsQuery<S extends OrgOwnerGrantSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgOwnerGrantFilter, OrgOwnerGrantOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgOwnerGrantSelect>;
}): Promise<{
  orgOwnerGrants: ConnectionResult<InferSelectResult<OrgOwnerGrantWithRelations, S>>;
}>;
export async function fetchOrgOwnerGrantsQuery(params: {
  selection: ListSelectionConfig<OrgOwnerGrantSelect, OrgOwnerGrantFilter, OrgOwnerGrantOrderBy>;
}) {
  const args = buildListSelectionArgs<
    OrgOwnerGrantSelect,
    OrgOwnerGrantFilter,
    OrgOwnerGrantOrderBy
  >(params.selection);
  return getClient().orgOwnerGrant.findMany(args).unwrap();
}
/**
 * Records of ownership transfers and grants between members
 *
 * @example
 * ```ts
 * await prefetchOrgOwnerGrantsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgOwnerGrantsQuery<S extends OrgOwnerGrantSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgOwnerGrantFilter, OrgOwnerGrantOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgOwnerGrantSelect>;
  }
): Promise<void>;
export async function prefetchOrgOwnerGrantsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgOwnerGrantSelect, OrgOwnerGrantFilter, OrgOwnerGrantOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgOwnerGrantSelect,
    OrgOwnerGrantFilter,
    OrgOwnerGrantOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgOwnerGrantKeys.list(args),
    queryFn: () => getClient().orgOwnerGrant.findMany(args).unwrap(),
  });
}
