/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgInviteKeys } from '../query-keys';
import type {
  OrgInviteSelect,
  OrgInviteWithRelations,
  OrgInviteFilter,
  OrgInviteOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgInviteSelect,
  OrgInviteWithRelations,
  OrgInviteFilter,
  OrgInviteOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgInvitesQueryKey = orgInviteKeys.list;
/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgInvitesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgInvitesQuery<
  S extends OrgInviteSelect,
  TData = {
    orgInvites: ConnectionResult<InferSelectResult<OrgInviteWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgInviteFilter, OrgInviteOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgInviteSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgInvites: ConnectionResult<InferSelectResult<OrgInviteWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgInvitesQuery(
  params: {
    selection: ListSelectionConfig<OrgInviteSelect, OrgInviteFilter, OrgInviteOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<OrgInviteSelect, OrgInviteFilter, OrgInviteOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgInviteKeys.list(args),
    queryFn: () => getClient().orgInvite.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 *
 * @example
 * ```ts
 * const data = await fetchOrgInvitesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgInvitesQuery<S extends OrgInviteSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgInviteFilter, OrgInviteOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgInviteSelect>;
}): Promise<{
  orgInvites: ConnectionResult<InferSelectResult<OrgInviteWithRelations, S>>;
}>;
export async function fetchOrgInvitesQuery(params: {
  selection: ListSelectionConfig<OrgInviteSelect, OrgInviteFilter, OrgInviteOrderBy>;
}) {
  const args = buildListSelectionArgs<OrgInviteSelect, OrgInviteFilter, OrgInviteOrderBy>(
    params.selection
  );
  return getClient().orgInvite.findMany(args).unwrap();
}
/**
 * Invitation records sent to prospective members via email, with token-based redemption and expiration
 *
 * @example
 * ```ts
 * await prefetchOrgInvitesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgInvitesQuery<S extends OrgInviteSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgInviteFilter, OrgInviteOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgInviteSelect>;
  }
): Promise<void>;
export async function prefetchOrgInvitesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgInviteSelect, OrgInviteFilter, OrgInviteOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<OrgInviteSelect, OrgInviteFilter, OrgInviteOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: orgInviteKeys.list(args),
    queryFn: () => getClient().orgInvite.findMany(args).unwrap(),
  });
}
