/**
 * Join table linking profiles to individual permissions they include
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgProfilePermissionKeys } from '../query-keys';
import type {
  OrgProfilePermissionSelect,
  OrgProfilePermissionWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  OrgProfilePermissionSelect,
  OrgProfilePermissionWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgProfilePermissionQueryKey = orgProfilePermissionKeys.detail;
/**
 * Join table linking profiles to individual permissions they include
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgProfilePermissionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgProfilePermissionQuery<
  S extends OrgProfilePermissionSelect,
  TData = {
    orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgProfilePermissionSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgProfilePermissionQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgProfilePermissionSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgProfilePermissionSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgProfilePermissionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgProfilePermission.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Join table linking profiles to individual permissions they include
 *
 * @example
 * ```ts
 * const data = await fetchOrgProfilePermissionQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgProfilePermissionQuery<S extends OrgProfilePermissionSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgProfilePermissionSelect>;
}): Promise<{
  orgProfilePermission: InferSelectResult<OrgProfilePermissionWithRelations, S> | null;
}>;
export async function fetchOrgProfilePermissionQuery(params: {
  id: string;
  selection: SelectionConfig<OrgProfilePermissionSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgProfilePermissionSelect>(params.selection);
  return getClient()
    .orgProfilePermission.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Join table linking profiles to individual permissions they include
 *
 * @example
 * ```ts
 * await prefetchOrgProfilePermissionQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgProfilePermissionQuery<S extends OrgProfilePermissionSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgProfilePermissionSelect>;
  }
): Promise<void>;
export async function prefetchOrgProfilePermissionQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgProfilePermissionSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgProfilePermissionSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgProfilePermissionKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgProfilePermission.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
