/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgPermissionKeys } from '../query-keys';
import type {
  OrgPermissionSelect,
  OrgPermissionWithRelations,
  OrgPermissionFilter,
  OrgPermissionOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgPermissionSelect,
  OrgPermissionWithRelations,
  OrgPermissionFilter,
  OrgPermissionOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgPermissionsQueryKey = orgPermissionKeys.list;
/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgPermissionsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgPermissionsQuery<
  S extends OrgPermissionSelect,
  TData = {
    orgPermissions: ConnectionResult<InferSelectResult<OrgPermissionWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgPermissionFilter, OrgPermissionOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgPermissionSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgPermissions: ConnectionResult<InferSelectResult<OrgPermissionWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgPermissionsQuery(
  params: {
    selection: ListSelectionConfig<OrgPermissionSelect, OrgPermissionFilter, OrgPermissionOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgPermissionSelect,
    OrgPermissionFilter,
    OrgPermissionOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgPermissionKeys.list(args),
    queryFn: () => getClient().orgPermission.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * const data = await fetchOrgPermissionsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgPermissionsQuery<S extends OrgPermissionSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgPermissionFilter, OrgPermissionOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgPermissionSelect>;
}): Promise<{
  orgPermissions: ConnectionResult<InferSelectResult<OrgPermissionWithRelations, S>>;
}>;
export async function fetchOrgPermissionsQuery(params: {
  selection: ListSelectionConfig<OrgPermissionSelect, OrgPermissionFilter, OrgPermissionOrderBy>;
}) {
  const args = buildListSelectionArgs<
    OrgPermissionSelect,
    OrgPermissionFilter,
    OrgPermissionOrderBy
  >(params.selection);
  return getClient().orgPermission.findMany(args).unwrap();
}
/**
 * Defines available permissions as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * await prefetchOrgPermissionsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgPermissionsQuery<S extends OrgPermissionSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgPermissionFilter, OrgPermissionOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgPermissionSelect>;
  }
): Promise<void>;
export async function prefetchOrgPermissionsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgPermissionSelect, OrgPermissionFilter, OrgPermissionOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgPermissionSelect,
    OrgPermissionFilter,
    OrgPermissionOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgPermissionKeys.list(args),
    queryFn: () => getClient().orgPermission.findMany(args).unwrap(),
  });
}
