/**
 * Append-only log of hierarchy edge grants and revocations; triggers apply changes to the edges table
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgChartEdgeGrantKeys } from '../query-keys';
import type {
  OrgChartEdgeGrantSelect,
  OrgChartEdgeGrantWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  OrgChartEdgeGrantSelect,
  OrgChartEdgeGrantWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgChartEdgeGrantQueryKey = orgChartEdgeGrantKeys.detail;
/**
 * Append-only log of hierarchy edge grants and revocations; triggers apply changes to the edges table
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgChartEdgeGrantQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgChartEdgeGrantQuery<
  S extends OrgChartEdgeGrantSelect,
  TData = {
    orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgChartEdgeGrantSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgChartEdgeGrantQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgChartEdgeGrantSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgChartEdgeGrantSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgChartEdgeGrantKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgChartEdgeGrant.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Append-only log of hierarchy edge grants and revocations; triggers apply changes to the edges table
 *
 * @example
 * ```ts
 * const data = await fetchOrgChartEdgeGrantQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgChartEdgeGrantQuery<S extends OrgChartEdgeGrantSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgChartEdgeGrantSelect>;
}): Promise<{
  orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S> | null;
}>;
export async function fetchOrgChartEdgeGrantQuery(params: {
  id: string;
  selection: SelectionConfig<OrgChartEdgeGrantSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgChartEdgeGrantSelect>(params.selection);
  return getClient()
    .orgChartEdgeGrant.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Append-only log of hierarchy edge grants and revocations; triggers apply changes to the edges table
 *
 * @example
 * ```ts
 * await prefetchOrgChartEdgeGrantQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgChartEdgeGrantQuery<S extends OrgChartEdgeGrantSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgChartEdgeGrantSelect>;
  }
): Promise<void>;
export async function prefetchOrgChartEdgeGrantQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgChartEdgeGrantSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgChartEdgeGrantSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgChartEdgeGrantKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgChartEdgeGrant.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
