/**
 * Custom query hook for orgPermissionsGetMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { OrgPermissionsGetMaskVariables } from '../../orm/query';
export type { OrgPermissionsGetMaskVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const orgPermissionsGetMaskQueryKey = customQueryKeys.orgPermissionsGetMask;
/**
 * Query hook for orgPermissionsGetMask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgPermissionsGetMaskQuery({ variables: { ids } });
 *
 * if (data?.orgPermissionsGetMask) {
 *   console.log(data.orgPermissionsGetMask);
 * }
 * ```
 */
export function useOrgPermissionsGetMaskQuery<
  TData = {
    orgPermissionsGetMask: string | null;
  },
>(
  params?: {
    variables?: OrgPermissionsGetMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgPermissionsGetMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgPermissionsGetMaskQuery<
  TData = {
    orgPermissionsGetMask: string | null;
  },
>(
  params?: {
    variables?: OrgPermissionsGetMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgPermissionsGetMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: orgPermissionsGetMaskQueryKey(variables),
    queryFn: () => getClient().query.orgPermissionsGetMask(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch orgPermissionsGetMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgPermissionsGetMaskQuery({ variables: { ids } });
 * ```
 */
export async function fetchOrgPermissionsGetMaskQuery(params?: {
  variables?: OrgPermissionsGetMaskVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.orgPermissionsGetMask(variables).unwrap();
}
/**
 * Prefetch orgPermissionsGetMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgPermissionsGetMaskQuery(queryClient, { variables: { ids } });
 * ```
 */
export async function prefetchOrgPermissionsGetMaskQuery(
  queryClient: QueryClient,
  params?: {
    variables?: OrgPermissionsGetMaskVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: orgPermissionsGetMaskQueryKey(variables),
    queryFn: () => getClient().query.orgPermissionsGetMask(variables).unwrap(),
  });
}
