-- Revert: schemas/routing_public/tables/platform_site_app_links/constraints/platform_site_app_links_site_id_platform_app_identifier_key/constraint


ALTER TABLE routing_public.platform_site_app_links 
  DROP CONSTRAINT platform_site_app_links_site_id_platform_app_identifier_key RESTRICT;