-- Revert: schemas/catalog_private/tables/bindings/indexes/bindings_graph_id_key_database_id_owner_scope_owner_key_idx


DROP INDEX catalog_private.bindings_graph_id_key_database_id_owner_scope_owner_key_idx;