-- Revert: schemas/platform_routing_public/tables/platform_hostname_bindings/indexes/platform_hostname_bindings_domain_id_idx


DROP INDEX platform_routing_public.platform_hostname_bindings_domain_id_idx;