-- Revert: schemas/myapp_capabilities_public/tables/org_capability_defaults/indexes/org_capability_defaults_entity_id_idx


DROP INDEX myapp_capabilities_public.org_capability_defaults_entity_id_idx;


