-- Revert: schemas/myapp_profiles_public/tables/org_profile_capabilities/triggers/org_profile_capabilities_recompute_trg


DROP TRIGGER org_profile_capabilities_recompute_trg ON myapp_profiles_public.org_profile_capabilities;


