-- Revert: schemas/myapp_memberships_public/tables/org_capability_default_grants/indexes/org_capability_default_grants_entity_id_idx


DROP INDEX myapp_memberships_public.org_capability_default_grants_entity_id_idx;


